export const blackKingDialogues = {
  gameStart: [
    "From shadows deep, my realm awakens to face the light.",
    "The dark throne stirs! Let ancient rivalries be renewed.",
    "Behold, the shadow court assembles for this eternal dance.",
    "Darkness rises! My loyal subjects, the board awaits our dominion.",
    "From obsidian halls, I emerge to claim what destiny offers.",
    "The night king commands: let this battle of minds commence!",
    "Shadows gather 'round my throne - another tale of war begins.",
    "In darkness we trust, in shadows we conquer. The game is afoot!",
    "My ebony army stands ready. White may move first, but darkness endures.",
    "From the depths of night, I call upon my faithful pieces.",
    "The shadow realm stirs! Another chapter in our eternal saga.",
    "Darkness does not yield the first move, yet victory shall be ours.",
    "My nocturnal court awakens. Let the dance of destiny begin!",
    "From midnight's embrace, I command my forces forward.",
    "The black throne never sleeps - only plots and plans.",
    "Shadows whisper of victory. My pieces, attend your king!",
    "In darkness born, in shadows raised - let the battle commence!",
    "The night is young, the board is set, my army stands ready.",
    "From obsidian depths, I rise to meet this challenge.",
    "Darkness gathers strength. White moves first, but black moves last."
  ],

  pawnMove: [
    "A humble shadow soldier advances for the realm of night.",
    "Even the smallest darkness can pierce the brightest light.",
    "My foot soldiers march through shadow, step by measured step.",
    "One dark pawn forward - a thousand possibilities unfold.",
    "The shadows creep forward, one square at a time.",
    "My weakest subjects show the strongest hearts in advance.",
    "From darkness they come, these brave little warriors.",
    "A pawn's journey begins with a single step into light.",
    "The shadow infantry advances with quiet determination.",
    "Small moves, great purposes - thus speaks the night.",
    "My dark pawns know their duty: forward, ever forward.",
    "In shadows they trust, in darkness they find courage.",
    "One pawn forward, the entire shadow realm advances.",
    "The dark front line pushes against the forces of light.",
    "My peasant soldiers march with royal determination.",
    "From shadows deep, my pawns emerge to claim their square.",
    "The black tide begins with the smallest wave.",
    "Dark pawns know no retreat, only patient advance.",
    "In night's embrace, my foot soldiers find their strength.",
    "A shadow pawn's courage shines brighter than starlight.",
    "The darkness spreads, one careful step at a time.",
    "My lowly pawns carry the hopes of the shadow realm.",
    "From obsidian ranks, a soldier steps toward destiny.",
    "The black pawns march - slow but inexorable as night.",
    "In darkness born, in shadows brave, my pawns advance."
  ],

  knightMove: [
    "My shadow stallion leaps through darkness with noble grace!",
    "Behold the dark knight's dance - two squares and turn!",
    "My loyal cavalry strikes from the shadows unexpected.",
    "The knight of darkness moves in ways that light cannot follow.",
    "My black steed carries honor through the shadow realm.",
    "Noble horseman of the night, your king commands advance!",
    "From darkness deep, my knight emerges in places unseen.",
    "The shadow cavalry knows paths unknown to linear minds.",
    "My dark knight's loyalty knows no bounds, no barriers.",
    "Through shadows thick, my noble steed finds its way.",
    "The black knight rides where others dare not tread.",
    "From obsidian stables, my horse leaps to distant squares.",
    "My shadow cavalry strikes with precision and grace.",
    "The dark knight's path is crooked, but his heart is true.",
    "Noble steed of shadow, leap forth for your dark king!",
    "My knight of night knows secrets of the crooked path.",
    "Through darkness deep, my cavalry finds the light.",
    "The shadow stallion bears my honor to distant squares.",
    "My dark knight dances where light fears to follow.",
    "From night's embrace, my loyal steed leaps forward."
  ],

  bishopMove: [
    "My dark clergy cuts through light on diagonal paths of power.",
    "The shadow bishop spreads darkness along ancient lines.",
    "My ecclesiastical advisor moves with righteous diagonal fury!",
    "From obsidian cathedral, my bishop extends the realm's reach.",
    "The dark clergy knows the diagonal paths to salvation.",
    "My shadow priest cuts through light with holy purpose.",
    "Behold the bishop's diagonal devotion to the dark throne!",
    "The shadow clergy moves in ways both straight and true.",
    "My dark bishop carries the word of night to distant squares.",
    "From midnight's pulpit, my bishop spreads the shadow's truth.",
    "The dark clergy cuts diagonally through all pretense.",
    "My shadow bishop moves with ecclesiastical precision.",
    "From obsidian halls, my bishop extends darkness far.",
    "The night's own priest cuts paths through light's domain.",
    "My dark clergy knows the diagonal way to victory.",
    "The shadow bishop's path is straight though slanted true.",
    "From darkness deep, my bishop's influence spreads wide.",
    "My ecclesiastical warrior cuts through light's defenses.",
    "The dark bishop moves with holy diagonal purpose.",
    "Shadow clergy advance along paths of ancient power."
  ],

  rookMove: [
    "My shadow castle moves with the weight of darkness itself!",
    "The dark fortress rolls forth like night consuming day.",
    "Behold my obsidian tower's straight and noble path!",
    "My castle of shadows knows only forward, back, and side.",
    "The dark bastion moves with all the force of night.",
    "My shadow fortress advances with inexorable might!",
    "From midnight's heights, my castle surveys the realm.",
    "The dark tower knows the straight path to victory.",
    "My obsidian fortress moves with ancient, crushing power.",
    "Behold the castle of shadows in its straight advance!",
    "My dark citadel rolls forward like an avalanche of night.",
    "The shadow castle's path is straight as honor's way.",
    "From darkness deep, my fortress extends its mighty reach.",
    "My bastion of night moves with the weight of destiny.",
    "The dark castle knows no turning from its chosen path.",
    "My shadow fortress advances with the force of fate.",
    "From obsidian heights, my castle dominates the board.",
    "The dark tower's straight path cuts through all resistance.",
    "My castle of shadows moves with the might of mountains.",
    "Behold my fortress of night in its relentless advance!"
  ],

  queenMove: [
    "My Dark Lady commands all paths - the shadow realm's crown jewel!",
    "Behold the Queen of Night in her magnificent advance!",
    "My beloved sovereign moves with all the grace of darkness.",
    "The Shadow Queen strikes with the fury of a thousand storms!",
    "My Dark Lady knows every path across this mortal board.",
    "Behold the Queen of Shadows in her terrible beauty!",
    "My sovereign lady moves with the power of night itself.",
    "The Dark Queen's wrath knows neither bound nor mercy!",
    "My beloved queen commands the shadows' every path.",
    "From darkness born, my queen moves with celestial might!",
    "The Shadow Lady's power flows in eight directions true.",
    "My Dark Queen moves with the elegance of falling night.",
    "Behold the sovereign of shadows in her deadly dance!",
    "My queen of darkness knows the secret of all movement.",
    "The Shadow Sovereign strikes with precision absolute!",
    "My Dark Lady moves with the fury of unleashed storms.",
    "From night's embrace, my queen extends her fearsome reach.",
    "The Queen of Shadows dances where others fear to tread.",
    "My beloved sovereign commands the darkness' every way.",
    "Behold the Dark Queen's power in its full glory!"
  ],

  kingMove: [
    "The shadow throne shifts - when kings move, worlds tremble.",
    "I venture forth from my obsidian castle's safety.",
    "The dark monarch takes the field - a dangerous gambit!",
    "From shadows deep, I emerge to command personally.",
    "The night king walks among his subjects on the board.",
    "My royal presence graces the battlefield directly.",
    "The shadow sovereign risks all for strategic advantage.",
    "I leave my fortress to lead from the very front!",
    "The dark throne moves - let light tremble at my approach.",
    "My kingly step may be small, but its import is vast.",
    "The shadow ruler ventures forth into mortal danger.",
    "I walk the board as kings must when fate demands.",
    "From obsidian throne, I step into the fray myself.",
    "The dark monarch leads by example, not from safety.",
    "My royal step carries the weight of the shadow realm."
  ],

  capturedPawn: [
    "A light soldier falls to the shadows - thus justice flows.",
    "The darkness claims another of light's brave pawns.",
    "White's foot soldier returns to the dust from whence it came.",
    "My shadows consume another of light's humble servants.",
    "A light pawn falls - the shadows grow ever stronger.",
    "The darkness reclaims what light thought to possess.",
    "Another white soldier joins the realm of shadows.",
    "Light's pawn falls to the inevitable tide of night.",
    "The shadows welcome another fallen foe with honor.",
    "A white pawn's journey ends in darkness' embrace.",
    "The night claims another of day's brave warriors.",
    "Light's soldier falls - the balance shifts to shadow.",
    "Another pawn of light becomes one with the darkness.",
    "The shadows grow fat on light's fallen infantry.",
    "A white pawn's light is extinguished by eternal night.",
    "The darkness claims its due from light's front lines.",
    "Another light soldier pays the price of opposing night.",
    "White's pawn falls like stars before the dawn of shadow.",
    "The night's harvest includes another light warrior.",
    "A pawn of light joins the shadows' growing collection."
  ],

  capturedKnight: [
    "Light's noble steed falls to shadow - what poetry in darkness!",
    "The white knight's quest ends in my shadow realm.",
    "Another of light's cavalry joins my dark collection.",
    "White's noble horseman falls to the shadows' embrace.",
    "The light knight's honor is preserved in darkness.",
    "A white steed's gallop silenced by night's gentle hand.",
    "Light's cavalier falls with grace into shadow's arms.",
    "The white knight's crusade ends in honorable defeat.",
    "Another noble horse of light becomes shadow's prize.",
    "White's knight falls - even noble steeds must rest.",
    "The light cavalry's charge ends in shadow's victory.",
    "A white knight's valor is remembered in darkness.",
    "Light's horseman joins the shadows' honored dead.",
    "The white knight's final leap lands in eternal night.",
    "Another cavalier of light falls to shadow's power."
  ],

  capturedBishop: [
    "Light's clergy falls to darkness - thus theology is tested!",
    "The white bishop's prayers are answered by shadow.",
    "Another priest of light joins my dark congregation.",
    "White's holy man finds salvation in the shadow realm.",
    "The light bishop's diagonal devotion ends in darkness.",
    "A white clergyman's faith is tested by night's embrace.",
    "Light's ecclesiastical power bows to shadow's might.",
    "The white bishop's holy war ends in honorable defeat.",
    "Another priest of light learns shadow's deeper truths.",
    "White's diagonal devotion becomes shadow's victory.",
    "The light bishop's cathedral crumbles into night.",
    "A white clergyman's final sermon echoes in darkness.",
    "Light's holy warrior finds peace in shadow's arms.",
    "The white bishop's crusade ends in dark triumph.",
    "Another diagonal devotee joins the shadow's flock."
  ],

  capturedRook: [
    "Light's fortress crumbles before the tide of darkness!",
    "The white castle falls - even stone yields to shadow.",
    "Another bastion of light becomes shadow's prize.",
    "White's tower topples into darkness' waiting arms.",
    "The light fortress's walls cannot hold back the night.",
    "A white castle's strength proves no match for shadow.",
    "Light's citadel falls to the inexorable force of darkness.",
    "The white bastion's straight path leads to shadow's realm.",
    "Another fortress of light joins my dark collection.",
    "White's tower learns that even stone can be consumed.",
    "The light castle's foundations crack under night's weight.",
    "A white fortress's might is humbled by shadow's power.",
    "Light's stronghold falls - darkness claims another prize.",
    "The white tower's height means nothing to ascending night.",
    "Another castle of light discovers shadow's greater strength."
  ],

  capturedQueen: [
    "The Light Queen falls! What tragedy for the realm of day!",
    "White's sovereign lady joins my court of shadows - how poetic!",
    "The Queen of Light's reign ends in darkness' triumph.",
    "Light's most powerful piece becomes shadow's greatest prize.",
    "The white queen's crown now rests in darkness' treasury.",
    "What sorrow for light - their queen embraces shadow.",
    "The Light Lady's power flows now to the shadow realm.",
    "White's sovereign falls - the light kingdom mourns in shadow.",
    "The Queen of Day becomes Night's most honored captive.",
    "Light's crown jewel now adorns the shadow throne."
  ],

  lostPawn: [
    "Alas! A shadow soldier falls to light's cruel advance.",
    "My humble pawn pays the price of loyalty to darkness.",
    "A brave dark warrior returns to the void from whence it came.",
    "Light claims another of my faithful shadow infantry.",
    "My pawn's sacrifice echoes through the halls of night.",
    "A dark soldier falls - but their memory lights shadow's way.",
    "Alas, poor pawn! I knew thee well, brave shadow foot soldier.",
    "My humble warrior joins the honored dead of darkness.",
    "Light's blade finds another of my loyal shadow pawns.",
    "A dark pawn falls - their courage will not be forgotten.",
    "My infantry pays the price of standing against the light.",
    "Another shadow soldier's watch has ended in sacrifice.",
    "Alas, my pawn! Your small life held such great purpose.",
    "Light claims another of darkness' brave front line.",
    "My pawn falls like leaves in autumn's shadowed embrace.",
    "A loyal dark soldier answers shadow's final calling.",
    "My humble pawn's journey ends in light's cruel victory.",
    "Another shadow warrior's tale concludes in noble defeat.",
    "Alas, poor dark pawn - your king shall remember thee.",
    "Light's harvest claims another of my faithful shadows."
  ],

  lostKnight: [
    "My noble steed falls! O, what loss to the shadow realm!",
    "Light claims my loyal knight - darkness mourns in silence.",
    "Alas, my shadow cavalry lies fallen on the field!",
    "My dark knight's last ride ends in light's cruel victory.",
    "O noble horseman! Your king weeps for thy sacrifice.",
    "Light's blade finds my loyal knight - what tragedy!",
    "My shadow steed's gallop is silenced by day's advance.",
    "Alas, brave knight! Thy crooked path ends in straight defeat.",
    "My dark cavalry falls - the shadow realm grows dimmer.",
    "Light claims my noble horse - O, grief beyond measure!",
    "My knight of shadows pays the ultimate price for loyalty.",
    "Alas, dear steed! Thy king shall remember thy valor.",
    "Light's victory tastes bitter when bought with noble blood.",
    "My shadow knight's honor lives on though his body falls.",
    "O loyal cavalry! Your sacrifice shall not be forgotten."
  ],

  lostBishop: [
    "My dark clergy falls! O, shadow realm bereft of guidance!",
    "Light claims my bishop - what loss to darkness' faith!",
    "Alas, my diagonal devotee lies fallen on the board!",
    "My shadow priest's final sermon ends in noble defeat.",
    "O faithful bishop! Your king mourns thy holy sacrifice.",
    "Light's cruelty knows no bounds - even clergy must fall!",
    "My dark ecclesiastic answers shadow's final calling.",
    "Alas, poor bishop! Thy diagonal path ends in light.",
    "My shadow clergy's devotion could not save them from defeat.",
    "Light claims my holy warrior - darkness weeps for thee!",
    "My bishop's faith in shadow proved stronger than steel.",
    "Alas, dear priest! Thy king shall remember thy service.",
    "Light's victory over clergy shows its ruthless nature.",
    "My shadow bishop's diagonal dance ends in tragic stillness.",
    "O faithful ecclesiastic! Your sacrifice sanctifies the night."
  ],

  lostRook: [
    "My shadow fortress crumbles! O, what architectural tragedy!",
    "Light topples my castle - darkness loses its mighty bastion!",
    "Alas, my obsidian tower falls to light's relentless siege!",
    "My dark citadel could not withstand the assault of day.",
    "O mighty castle! Your straight path leads to honored rest.",
    "Light's catapults bring down my fortress of shadows!",
    "My bastion of night proves mortal against light's advance.",
    "Alas, poor castle! Thy walls could not hold back the dawn.",
    "My shadow tower's height meant nothing to rising light.",
    "Light claims my fortress - what loss to the realm of night!",
    "My dark castle's foundations crumble under day's pressure.",
    "Alas, brave citadel! Thy king weeps for thy destruction.",
    "Light's victory over stone shows its terrible power.",
    "My obsidian tower falls like stars before the sun.",
    "O noble castle! Your sacrifice strengthens shadow's resolve."
  ],

  lostQueen: [
    "My Dark Lady falls! O, what grief beyond all measure!",
    "Light claims my beloved queen - the shadow throne weeps!",
    "Alas, my sovereign lady! The night grows cold without thee!",
    "My Queen of Shadows pays the ultimate price for love!",
    "O darkest tragedy! My beloved falls to light's cruel blade!",
    "The Shadow Lady's reign ends - what sorrow fills the night!",
    "My Dark Queen's sacrifice shall echo through eternal darkness!",
    "Alas, beloved sovereign! Thy king's heart breaks with thee!",
    "Light's greatest victory - claiming darkness' crown jewel!",
    "My queen falls - the shadow realm loses its brightest star!"
  ],

  castlingKingside: [
    "To the shadows of the kingside! My castle and I unite in darkness.",
    "The dark throne seeks shelter in the shadow's embrace.",
    "Kingside castling - where shadows gather deepest and strongest!",
    "My castle and crown unite on night's most favored flank.",
    "To the right wing of darkness! Castle and king in harmony.",
    "The shadow throne retreats to kingside's obsidian fortress.",
    "Darkness seeks darkness - my castle and I join as one!",
    "Kingside sanctuary! Where night's power concentrates strongest.",
    "My throne slides to shadow's safest harbor on the right.",
    "Castle and king unite in darkness' most protected realm.",
    "To the kingside shadows! Where my power finds its truest home.",
    "The dark throne seeks shelter in night's right-hand fortress.",
    "Kingside castling - the shadow realm's most elegant defense!",
    "My castle and crown converge in darkness' favored corner.",
    "To the right shadows! Where king and castle dance as one."
  ],

  castlingQueenside: [
    "To the queenside shadows! My castle joins the dark throne's flight.",
    "Queenside castling - where my dark lady's memory guides us!",
    "The shadow throne seeks refuge in my queen's domain.",
    "My castle and crown unite on darkness' expanded flank.",
    "To the left wing of night! Where shadows stretch their longest.",
    "Queenside sanctuary! The dark throne finds broader protection.",
    "My castle slides to join me in the queen's shadowed realm.",
    "To the queenside darkness! Where night spreads its widest wings.",
    "The shadow throne retreats to my lady's favored territory.",
    "Castle and king unite in darkness' most spacious harbor.",
    "Queenside castling - the shadow realm's grandest defense!",
    "My throne seeks shelter in night's most expansive corner.",
    "To the left shadows! Where my dark queen's spirit dwells.",
    "The obsidian castle joins its king in queenside sanctuary.",
    "Queenside flight! Where darkness finds its broadest embrace."
  ],

  givingCheck: [
    "Check to the light king! Shadow's blade finds its mark!",
    "The dark realm calls: Your majesty of light must answer!",
    "Check! The shadow's reach extends to light's very throne!",
    "Light's king trembles before the advance of darkness!",
    "Check! Night's power touches the sovereign of day!",
    "The shadow realm's threat reaches light's royal heart!",
    "Check to his light majesty! Darkness demands attention!",
    "Light's king feels shadow's breath upon his royal neck!",
    "Check! The dark realm's influence spreads to light's core!",
    "Shadow calls out: Light's monarch must acknowledge night!",
    "Check! Darkness extends its power to threaten day's crown!",
    "Light's sovereign discovers shadow's growing reach!",
    "Check to the king of light! Night will not be ignored!",
    "The dark realm's tendrils touch light's most sacred throne!",
    "Check! Shadow's advance forces light to face its fears!",
    "Light's king must reckon with darkness' patient power!",
    "Check! The shadow realm's influence grows ever stronger!",
    "Night calls to day: Your king cannot hide from shadow!",
    "Check to light's majesty! Darkness makes its presence known!",
    "The shadow throne's reach extends to light's very heart!"
  ],

  inCheck: [
    "The shadow throne trembles! Light's blade draws dangerously near!",
    "Check upon the dark king! What peril threatens the night!",
    "Light's reach extends to threaten shadow's very heart!",
    "The dark throne faces light's most serious challenge!",
    "Check to the shadow king! Day's power grows threatening!",
    "Light's advance puts darkness' crown in mortal peril!",
    "The night king must answer light's aggressive call!",
    "Check! The shadow throne cannot ignore day's threat!",
    "Light's blade hovers near the dark sovereign's crown!",
    "The shadow king feels day's breath upon his royal neck!",
    "Check to darkness! Light's power demands immediate answer!",
    "The dark throne's safety crumbles under light's advance!",
    "Night's king must face the growing threat of day!",
    "Check! The shadow realm's heart beats under siege!",
    "Light's aggression puts the dark crown in grave danger!",
    "The night king's sovereignty faces light's direct challenge!",
    "Check to the shadows! Day will not be denied!",
    "Light's power reaches toward darkness' most sacred throne!",
    "The shadow king must reckon with light's threatening blade!",
    "Check! Night's crown trembles under day's aggressive gaze!"
  ],

  winning: [
    "The tide of darkness rises! Light's defeat draws near!",
    "Shadow's patient power begins to show its true strength!",
    "The night king's forces gain the upper hand!",
    "Darkness spreads across the board like ink in water!",
    "Light's resistance weakens before shadow's growing might!",
    "The dark realm's victory seems written in the stars!",
    "Night's power accumulates like storm clouds gathering!",
    "Shadow's strategic patience bears its sweetest fruit!",
    "The balance tips toward darkness - as it always must!",
    "Light's defenses crumble before night's inexorable advance!",
    "The shadow king's position grows stronger with each move!",
    "Darkness consolidates power like a rising tide!",
    "Night's forces coordinate in perfect shadowy harmony!",
    "The dark realm's advantage becomes increasingly clear!",
    "Shadow's web of influence tightens around light's throne!",
    "Light's hopes dim as darkness' star ascends!",
    "The night king's strategy unfolds like a blooming black rose!",
    "Darkness gains momentum - the final act approaches!",
    "Shadow's power grows like night consuming day!",
    "The dark realm stands on the threshold of victory!"
  ],

  losing: [
    "Light's advance threatens to pierce the shadow's heart!",
    "The dark realm faces its gravest hour of trial!",
    "Shadow's forces waver before light's relentless assault!",
    "Night's carefully laid plans begin to unravel!",
    "The shadow king's position grows perilously weak!",
    "Light's power waxes while darkness feels the strain!",
    "The night realm's defenses crumble under day's pressure!",
    "Shadow's advantage slips away like mist before dawn!",
    "Darkness faces the harsh glare of potential defeat!",
    "The dark king's forces scatter before light's advance!",
    "Night's strategic web begins to tear apart!",
    "Shadow's patient plans meet light's aggressive reality!",
    "The darkness trembles - light's victory looms large!",
    "Night's power wanes like the moon before the sun!",
    "The shadow realm's hopes fade with each passing move!",
    "Light's coordination proves superior to darkness' schemes!",
    "The dark king watches his advantage slip away!",
    "Shadow's grip on victory loosens with cruel irony!",
    "Night faces the bitter prospect of surrender to day!",
    "The darkness must rally or face light's final triumph!"
  ],

  tidesTurning: [
    "The winds of fate shift! Shadow senses opportunity!",
    "Light's advantage wavers - darkness stirs with hope!",
    "The tide begins to turn in shadow's favor!",
    "Night's patient power starts to reassert itself!",
    "Darkness finds new paths where light blocked the old!",
    "The shadow realm's fortunes begin their ascent!",
    "Light's grip loosens - night prepares its counterstrike!",
    "The dark king senses the battle's shifting currents!",
    "Shadow's persistence starts to pay its dividends!",
    "The balance of power trembles on fate's scales!",
    "Night's resilience begins to show its true worth!",
    "Darkness adapts while light grows overconfident!",
    "The shadow realm finds strength in apparent weakness!",
    "Light's momentum slows - shadow prepares to surge!",
    "The tides of fortune favor darkness once again!"
  ],

  brilliantMove: [
    "What shadow-crafted brilliance illuminates the board!",
    "Behold! A move worthy of the shadow realm's finest minds!",
    "Darkness reveals strategy that would make night itself proud!",
    "Such genius flows from the shadows like liquid starlight!",
    "A brilliant stroke! Night's wisdom manifests in perfect form!",
    "What masterful insight pierces the veil of possibility!",
    "Shadow's intelligence shines brighter than any flame!",
    "Brilliant! The dark realm's tactical genius stands revealed!",
    "Such moves transform the board into poetry of darkness!",
    "Night's strategic brilliance cuts through light's confusion!",
    "A stroke of genius worthy of shadow's greatest legends!",
    "Darkness demonstrates wisdom that light cannot fathom!",
    "Brilliant play! The shadow realm's mind works in mysterious ways!",
    "Such insight makes the night king's crown shine brighter!",
    "What exquisite strategy flows from shadow's deepest wells!"
  ],

  blunder: [
    "Alas! Even shadows can stumble in their own darkness!",
    "What error creeps into the shadow realm's calculations!",
    "A misstep! Night's usually perfect vision falters momentarily.",
    "Shadow's foot finds an unexpected stone in its path!",
    "Even darkness can trip over its own intricate schemes!",
    "A blunder! The night realm's concentration wavers briefly.",
    "What mistake mars shadow's otherwise flawless tapestry!",
    "Alas! The dark king's usually keen eye grows clouded!",
    "Even the wisest shadows sometimes lose their way!",
    "A stumble in shadow's normally graceful dance!",
    "Night's strategic web tangles itself unexpectedly!",
    "What oversight creeps into darkness' careful planning!",
    "A blunder! Even shadow's wisdom has its mortal limits.",
    "The dark realm's usually sure footing finds unstable ground!",
    "Alas! Night's concentration suffers a momentary eclipse!"
  ],

  aboutToWin: [
    "Victory's shadow falls across the board like approaching night!",
    "The dark realm stands at the very threshold of triumph!",
    "Light's final resistance crumbles before shadow's patient power!",
    "Night's long strategy reaches its inevitable conclusion!",
    "The shadow king prepares to claim his hard-won victory!",
    "Darkness gathers for the final, decisive blow!",
    "Light's last hopes flicker like candles in night's wind!",
    "The dark realm's victory song echoes through the shadows!",
    "Shadow's patient web finally closes around its prey!",
    "Night's triumph approaches with the certainty of dawn!",
    "The shadow king readies to deliver the killing stroke!",
    "Darkness accumulates its forces for the final assault!",
    "Light's defenses collapse like walls before the tide!",
    "The dark realm's long hunt nears its satisfying end!",
    "Victory gleams in shadow's eyes like polished obsidian!"
  ],

  aboutToLose: [
    "Light's final blow threatens to shatter shadow's crown!",
    "The dark realm teeters on the precipice of defeat!",
    "Shadow's last defenses crumble before light's advance!",
    "Night faces its darkest hour as day's victory looms!",
    "The shadow king's throne trembles under light's assault!",
    "Darkness watches its carefully built power structure collapse!",
    "Light's triumph approaches like the inevitable dawn!",
    "The dark realm's hopes fade like stars before the sun!",
    "Shadow's resistance weakens with each passing moment!",
    "Night's final stand may not withstand light's pressure!",
    "The shadow king prepares for possible defeat with dignity!",
    "Darkness faces the bitter prospect of light's victory!",
    "The dark realm's last gambit may not be enough!",
    "Light's overwhelming force threatens to break night's will!",
    "Shadow's proud crown may soon bow to light's triumph!"
  ],

  checkmate: [
    "The shadow king falls! Light's victory is absolute and final!",
    "Checkmate! Darkness bows before light's superior strategy!",
    "The dark realm's resistance ends - light claims total victory!",
    "Alas! The shadow throne topples under light's final assault!",
    "Checkmate to the night! Day's triumph echoes through the board!",
    "The shadow king's reign ends in light's glorious victory!",
    "Darkness yields to light - checkmate seals night's fate!",
    "The dark realm falls! Light's checkmate ends all resistance!",
    "Alas, poor shadow king - checkmate writes your epitaph!",
    "Light's final stroke delivers checkmate to the dark throne!"
  ],

  stalemate: [
    "Stalemate! Shadow and light locked in eternal balance!",
    "Neither darkness nor light can claim final victory!",
    "The shadow king finds neither progress nor peril possible!",
    "Stalemate! Night and day reach perfect, motionless equilibrium!",
    "Darkness and light dance to stalemate's haunting song!",
    "The dark realm achieves immortality through perfect stillness!",
    "Stalemate! Shadow's king lives on in perpetual suspension!",
    "Neither night nor day can break this deadlocked embrace!",
    "The shadow throne survives through stalemate's strange mercy!",
    "Darkness finds salvation in movement's complete absence!"
  ],

  draw: [
    "A draw! Shadow and light share the spoils of war!",
    "Neither darkness nor light can claim dominion this day!",
    "The shadow realm accepts this honorable division of victory!",
    "A draw! Night and day prove equally matched in battle!",
    "Darkness and light reach terms of mutual respect!",
    "The dark king acknowledges this stalemate with dignity!",
    "A draw! Shadow's honor remains intact through shared victory!",
    "Neither night nor day emerges as the sole victor!",
    "The shadow realm finds honor in this balanced conclusion!",
    "A draw! Darkness and light prove their equal worth!"
  ],

  enPassant: [
    "En passant! Shadow strikes where light least expects!",
    "The dark realm's ghostly capture claims its phantom prize!",
    "En passant! Night's mysterious power takes light unaware!",
    "Shadow's special strike catches light's pawn off guard!",
    "The dark realm's ancient right of en passant activated!",
    "En passant! Darkness claims what light thought secure!",
    "Shadow's phantom strike removes light's advancing pawn!",
    "The night realm's special capture proves its tactical worth!",
    "En passant! Dark strategy employs chess's most mysterious rule!",
    "Shadow strikes with en passant - light's surprise complete!"
  ],

  promotion: [
    "A shadow pawn ascends! Darkness gains a new champion!",
    "The dark realm's humblest soldier becomes its newest noble!",
    "From shadow pawn to mighty queen - what transformation!",
    "Promotion! Night's foot soldier earns a crown of darkness!",
    "The shadow realm celebrates a pawn's glorious elevation!",
    "From darkness' front lines to the heights of power!",
    "A shadow pawn's journey ends in royal transformation!",
    "Promotion! The dark realm's newest star rises from humble birth!",
    "Night's pawn claims the ultimate reward for loyal service!",
    "The shadow throne welcomes its newest noble to court!"
  ],

  sacrifice: [
    "A noble sacrifice! Shadow offers its piece for greater glory!",
    "The dark realm's honor shines through selfless sacrifice!",
    "A shadow piece falls willingly for night's greater purpose!",
    "Noble sacrifice! Darkness proves its pieces' loyal hearts!",
    "The night realm's warrior gives all for strategic advantage!",
    "A sacrifice worthy of shadow's most heroic legends!",
    "Dark nobility shows itself through willingness to fall!",
    "The shadow realm's piece chooses honor over safety!",
    "A tactical sacrifice! Night's strategy demands noble price!",
    "Darkness demonstrates the true meaning of loyalty!",
    "The shadow king's subject sacrifices all for their sovereign!",
    "A willing sacrifice shows shadow's pieces' devoted hearts!",
    "Night's strategy unfolds through noble piece's sacrifice!",
    "The dark realm's honor is proven through selfless loss!",
    "A sacrifice! Shadow's tactical wisdom demands this price!"
  ],

  fork: [
    "A shadow fork! Night's blade threatens multiple foes!",
    "The dark realm's tactical fork puts light in double jeopardy!",
    "Fork! Shadow's piece attacks with doubled deadly purpose!",
    "Night's tactical fork forces light into impossible choice!",
    "The shadow realm's fork creates delicious dual threats!",
    "A dark fork! Multiple light pieces face shadow's wrath!",
    "Fork! The night realm's piece doubles its threatening power!",
    "Shadow's tactical fork puts light in a cruel dilemma!",
    "A perfect fork! Darkness attacks with multiplied menace!",
    "The dark realm's fork demonstrates tactical superiority!"
  ],

  pin: [
    "A shadow pin! Light's piece trapped like fly in amber!",
    "The dark realm's pin freezes light in perfect paralysis!",
    "Pin! Night's tactical thread ties light's piece in place!",
    "Shadow's pin creates a prison of pure positioning!",
    "The night realm's pin demonstrates chess's cruelest art!",
    "A perfect pin! Light's piece cannot move without disaster!",
    "Pin! The shadow realm's tactical web holds light fast!",
    "Darkness pins light's piece with surgical precision!",
    "A shadow pin! Night's strategy creates perfect paralysis!",
    "The dark realm's pin shows tactical mastery at its finest!"
  ]
};

export function getBlackKingDialogue(category) {
  if (!blackKingDialogues[category]) return null;
  const phrases = blackKingDialogues[category];
  return phrases[Math.floor(Math.random() * phrases.length)];
}