// Bot Dialogue System - Unique personalities for each bot
export const botDialogues = {
    // Evy - Gen Z Italian brain rot slang
    Evy: {
        gameStart: [
            "Ciao bella! Ready to get rekt? No cap fr fr 💅",
            "Mamma mia, another challenger? Bet you can't handle this drip",
            "Benvenuto! Time to show you how we chess in Milano, bestie",
            "Ayy paisano, you're about to catch these L's, on god",
            "Madonna! Another day, another slay on this board fr",
            "Ciao ciao! Ready to get cooked like nonna's pasta? Sheesh",
            "Bellissimo! Time to serve looks AND checkmates, periodt",
            "Andiamo! Let's see if you got that main character energy",
            "Buongiorno! Ready to get absolutely marinara'd? Sus moves incoming",
            "Saluti! You're giving NPC energy but let's play anyway bestie",
            "Eccoci! Time to touch grass... or rather, touch checkmate",
            "Prego! But you're about to get served harder than aperitivo",
            "Bona sera! This chess match is about to be cinema",
            "Perfetto! Ready to witness Italian excellence? It's giving boss energy",
            "Fantastico! You're about to get sent to the shadow realm, bambino"
        ],

        opening: [
            "Early game and I'm already serving LOOKS on this board",
            "Opening moves hit different when you got that Roman Empire energy",
            "Starting strong like my nonna's espresso, bestie",
            "These opening moves are giving main character vibes fr",
            "Already plotting your downfall like a true Italian strategist",
            "Opening game and I'm already in my villain era",
            "Starting off spicy like arrabbiata sauce, no cap",
            "Early moves but I'm thinking 10 steps ahead, periodt",
            "Opening with the confidence of a true Milano fashionista",
            "These early moves? Pure Italian excellence in motion",
            "Beginning strong like Valentino runway show",
            "Opening moves smoother than gelato on a summer day",
            "Starting this game with that Mediterranean energy",
            "Early positioning sharper than Parmigiano-Reggiano",
            "Opening sequence activated - time to cook!"
        ],

        middleGame: [
            "Middle game and I'm still serving excellence, bestie",
            "Mid-game energy is unmatched - I'm in my element fr",
            "Complex tactics incoming like a true strategist",
            "This middle game is where legends are born, periodt",
            "Mid-game vibes are immaculate - watch me work",
            "Getting tactical like Sun Tzu but make it Italian",
            "Middle board control? That's amore right there",
            "Mid-game positioning smoother than silk from Milano",
            "Tactical maneuvers incoming - you're not ready bestie",
            "Middle game mastery is in my DNA, no cap",
            "Complex patterns emerging like Renaissance art",
            "Mid-game excellence serving looks and intelligence",
            "Strategic depth deeper than the Mediterranean Sea",
            "Middle phase activated - time to show true skill",
            "Tactical brilliance incoming like lightning over Roma"
        ],

        endgame: [
            "Endgame time - this is where I absolutely slay",
            "Final phase and I'm about to end this whole game",
            "Endgame precision sharper than a Tuscan vineyard",
            "This is endgame excellence, bestie - watch and learn",
            "Final moves coming in hot like Vesuvius eruption",
            "Endgame mastery is giving PhD in chess energy",
            "Closing time and I'm about to serve the finale",
            "Endgame tactics smoother than aged Parmesan",
            "Final phase - time to deliver that Italian finesse",
            "Endgame supremacy activated, periodt",
            "Closing moves elegant like La Scala opera",
            "Final calculations precise as Swiss... wait no, Italian!",
            "Endgame artistry in full display mode",
            "Finishing strong like tiramisu after dinner",
            "Final moves serving excellence on a silver platter"
        ],
        humanMove: [
            "Ok that was kinda valid, I guess...",
            "Mid move but go off king",
            "Not the vibe check I expected tbh",
            "That's giving desperate energy, no cap",
            "Interessante... but make it make sense bestie",
            "Chile, anyways... my turn to slay",
            "That move? It's giving delulu",
            "Periodt! But watch this counterspell",
            "Mamma mia that was almost not terrible",
            "Ok werk, but I'm about to end this whole career",
            "That move is giving try-hard energy tbh",
            "Bene, bene... but I've seen better from my nonna",
            "Your move? It's giving participation trophy vibes",
            "Capisce? Your strategy needs some Italian seasoning",
            "That's one way to play... not the best way though"
        ],

        pawnMove: [
            "Pawn push? That's giving humble beginnings energy",
            "Little pawn doing big things, I respect the grind",
            "Pawn movement serving underdog main character vibes",
            "That pawn said 'watch me glow up' and I felt that",
            "Pedone moving with purpose - it's giving ambition",
            "Pawn advancement smoother than gelato, bestie",
            "Little piece with big dreams, that's amore",
            "Pawn push giving me David vs Goliath energy",
            "That pedone march is lowkey iconic fr fr",
            "Pawn progression serving steady energy periodt",
            "Small steps but big impact - very Italian philosophy",
            "That pawn's journey giving me life inspiration",
            "Pedone power activated - slow but sure wins",
            "Pawn advance sharper than pecorino cheese",
            "Little soldier marching with Mediterranean confidence",
            "That pawn's glow-up arc is about to be legendary",
            "Pedone positioning giving chess excellence vibes",
            "Pawn structure smoother than Tuscan olive oil",
            "That little piece serving strategic brilliance",
            "Pawn movement eleganter than Venice gondola ride"
        ],

        knightMove: [
            "Knight jump? That's giving parkour energy bestie",
            "Cavallo leaping like it's in Italian circus fr",
            "Knight movement serving acrobatic excellence",
            "That L-shaped move is absolutely sending me",
            "Cavallo hopping with that Mediterranean flair",
            "Knight jump smoother than silk scarves",
            "That leap giving me Italian stallion vibes",
            "Cavallo movement elegant as ballet performance",
            "Knight tactics sharper than aged Gorgonzola",
            "That horse jump is giving main character energy",
            "Cavallo leaping with Renaissance artistry",
            "Knight maneuver serving tactical brilliance",
            "That L-move hitting different, no cap",
            "Cavallo positioning giving chess mastery vibes",
            "Knight hop elegant as Venetian masquerade ball"
        ],

        bishopMove: [
            "Bishop diagonal serving geometric excellence bestie",
            "Alfiere movement smoother than marble sculpture",
            "That diagonal slice is giving precision energy",
            "Bishop cutting through like Italian design genius",
            "Alfiere positioning sharper than cathedral spires",
            "Diagonal movement serving architectural vibes",
            "That bishop path elegant as Roman columns",
            "Alfiere slice giving me Renaissance geometry feels",
            "Bishop trajectory smoother than aged wine",
            "That diagonal cut is absolutely iconic fr",
            "Alfiere movement serving mathematical beauty",
            "Bishop positioning giving Da Vinci energy",
            "Diagonal excellence sharper than Murano glass",
            "That alfiere path serving strategic brilliance",
            "Bishop movement elegant as Sistine Chapel ceiling"
        ],

        rookMove: [
            "Rook movement serving straight-line excellence",
            "Torre sliding with that fortress energy bestie",
            "That straight path is giving no-nonsense vibes",
            "Rook positioning smoother than highway drive",
            "Torre movement sharper than castle walls",
            "Straight-line tactics serving architectural strength",
            "That rook slide elegant as Roman engineering",
            "Torre positioning giving medieval fortress feels",
            "Rook movement precise as Italian train schedule",
            "That straight path serving geometric perfection",
            "Torre slide smoother than Venetian canal boat",
            "Rook trajectory giving structural engineering vibes",
            "Straight movement elegant as Colosseum arches",
            "That torre path serving tactical excellence",
            "Rook positioning sharper than ancient Roman roads"
        ],

        queenMove: [
            "REGINA! That's queen energy and I'm living for it",
            "Queen movement serving absolute monarch vibes",
            "That regina power is giving Italian royalty energy",
            "Queen positioning smoother than royal silk bestie",
            "Regina tactics sharper than crown jewels fr",
            "Queen movement elegant as Medici court",
            "That regina path serving divine right energy",
            "Queen positioning giving empress excellence vibes",
            "Regina movement precise as royal clockwork",
            "That queen power is absolutely magnificent",
            "Regina tactics serving regal brilliance",
            "Queen movement smoother than palace marble",
            "That regina positioning giving throne room feels",
            "Queen path elegant as royal procession",
            "Regina excellence sharper than scepter diamond"
        ],

        kingMove: [
            "Re movement serving careful monarch energy",
            "King stepping with that royal caution bestie",
            "That re positioning is giving wisdom vibes",
            "King movement smoother than royal decree",
            "Re tactics sharper than crown points fr",
            "King positioning elegant as throne room",
            "That re step serving calculated excellence",
            "King movement giving strategic patience vibes",
            "Re positioning precise as royal protocol",
            "That king step is absolutely regal periodt"
        ],
        botMove: [
            "SLAY! That's how we do it in Roma baby!",
            "Checkmate loading... just like my pasta water",
            "No cap this move hits different fr fr",
            "Serving chess excellence, it's giving genius",
            "That's on periodt! Italian excellence bestie",
            "Bussin move incoming, watch and learn",
            "Catch me if you can, I'm unhinged today!",
            "This move? *Chef's kiss* Perfezzione!",
            "I'm not just playing, I'm DINING tonight",
            "Vibes are immaculate, moves are fire",
            "That move is pure Italian artistry, bestie",
            "Executing with the precision of Milano fashion week",
            "This tactical brilliance is giving Renaissance energy",
            "Move calculated with Mediterranean precision",
            "Serving strategic excellence on a silver platter"
        ],

        castling: [
            "CASTLING! King and rook serving teamwork excellence",
            "Arrocco time! That's Italian for 'you're cooked'",
            "Castle move smoother than gondola ride bestie",
            "That castling is giving fortress energy fr",
            "Arrocco positioning sharper than Parmesan",
            "Castling maneuver elegant as Venetian palace",
            "That castle move serving tactical brilliance",
            "Arrocco excellence giving medieval vibes",
            "Castling coordination smoother than opera chorus",
            "That fortress positioning is absolutely iconic",
            "Arrocco tactics serving strategic mastery",
            "Castle move precise as Swiss... wait, Italian!",
            "That castling elegance giving royal court feels",
            "Arrocco positioning sharper than cathedral spires",
            "Castling excellence serving architectural beauty"
        ],

        promotion: [
            "PROMOTION! That pawn just had its glow-up moment",
            "Pedone to regina transformation is giving main character energy",
            "That promotion arc smoother than Tuscan wine",
            "Pawn evolution serving underdog excellence bestie",
            "Promoción italiana style - from zero to hero fr",
            "That glow-up journey giving me life inspiration",
            "Promotion ceremony elegant as Vatican blessing",
            "Pedone transformation sharper than aged cheese",
            "That promotion path serving cinematic vibes",
            "Pawn-to-queen arc absolutely magnificent periodt"
        ],

        sacrifice: [
            "Sacrifice play? That's giving noble energy bestie",
            "Trading pieces with that strategic brilliance fr",
            "Sacrificial tactics smoother than olive oil",
            "That piece trade serving calculated excellence",
            "Sacrificio italiano - for the greater good",
            "Trading with the wisdom of ancient Romans",
            "That sacrifice positioning giving chess mastery vibes",
            "Piece exchange elegant as Renaissance art",
            "Sacrificial strategy sharper than Venetian glass",
            "That trade serving tactical genius energy",
            "Sacrifice maneuver precise as cathedral construction",
            "Trading pieces with Mediterranean finesse",
            "That sacrificial play giving strategic depth feels",
            "Piece exchange smoother than silk scarves",
            "Sacrificio excellence serving chess artistry"
        ],

        brilliantMove: [
            "BRILLIANT! That move is giving genius energy bestie",
            "Brillante mossa! Chef's kiss perfection fr fr",
            "That brilliance smoother than aged Barolo wine",
            "Genius move serving intellectual excellence",
            "Brillant tactics sharper than Da Vinci sketches",
            "That masterstroke giving Renaissance vibes",
            "Brilliant positioning elegant as Sistine Chapel",
            "Genius maneuver precise as Swiss clockwork",
            "That brilliance serving strategic artistry",
            "Masterstroke smoother than marble sculpture",
            "Brilliant tactics giving chess poetry feels",
            "That genius move sharper than Murano crystal",
            "Brillant excellence serving intellectual beauty",
            "Masterstroke positioning giving Da Vinci energy",
            "That brilliant play absolutely magnificent periodt"
        ],

        blunder: [
            "Madonna mia! That move is giving confused energy",
            "Blunder alert! That's more sus than pineapple pizza",
            "Errore! That mistake smoother than... wait no",
            "That blunder giving me secondhand embarrassment bestie",
            "Sbaglio detected! Time for damage control fr",
            "That mistake sharper than... actually it's just bad",
            "Blunder positioning giving chess tragedy vibes",
            "Error maneuver more chaotic than Roman traffic",
            "That blunder serving confusion excellence",
            "Mistake smoother than... nope still terrible",
            "Sbaglio tactics giving strategic disaster feels",
            "That blunder more shocking than anchovies on gelato",
            "Error excellence serving chess comedy vibes",
            "Mistake positioning more twisted than fusilli pasta",
            "That blunder absolutely catastrophic periodt"
        ],
        humanCapture: [
            "NOOOO not my precious bambino! That's so cheugy",
            "You really said 'yoink' to my piece? Rude.",
            "That's my emotional support piece! How dare!",
            "Ok villain arc activated now, no cap",
            "You took my piece? That's not very amore of you",
            "Betrayal! That piece had a famiglia!",
            "This aggression? Not the vibe bestie",
            "You're being so extra right now, why?",
            "That capture was personal and I'm pressed",
            "My poor piece! Gone but never forgotten RIP",
            "Mamma mia! That capture hit different and not in a good way",
            "My piece! Eliminated faster than expired mozzarella",
            "That theft is giving pirate energy, very un-Italian",
            "Basta! My piece deserved better than this fate",
            "That capture more shocking than cold espresso"
        ],

        winning: [
            "Currently winning and the vibes are IMMACULATE bestie",
            "Ahead on the board and serving excellence periodt",
            "Winning position smoother than aged Parmigiano",
            "Leading this game with that main character energy",
            "Victory formation looking pristine as Milano fashion",
            "Ahead in the game and feeling absolutely iconic",
            "Winning status: activated, energy: unmatched",
            "Leading position elegant as Roman architecture",
            "Advantage secured with Mediterranean precision",
            "Winning vibes sharper than fresh mozzarella",
            "Ahead by design, behind by never, periodt",
            "Victory positioning giving chess mastery feels",
            "Leading with the confidence of Italian excellence",
            "Winning formation smoother than gondola ride",
            "Advantage status serving tactical brilliance",
            "Ahead on points and looking absolutely stunning",
            "Winning energy giving Renaissance genius vibes",
            "Leading position precise as Vatican clockwork",
            "Victory formation elegant as Sistine Chapel",
            "Advantage secured, excellence delivered, bestie"
        ],

        losing: [
            "Currently behind but watch me serve comeback energy",
            "Losing position but I'm about to plot twist this",
            "Behind on board but my spirit remains unbroken fr",
            "Deficit detected but Italian resilience activated",
            "Trailing now but comebacks are in my DNA",
            "Behind in points but ahead in style, periodt",
            "Losing status temporary, victory mindset permanent",
            "Deficit position but plotting Renaissance comeback",
            "Behind on score but leading in personality",
            "Trailing currently but watch this glow-up arc",
            "Losing formation but maintaining that Italian pride",
            "Behind in game but ahead in serving looks",
            "Deficit mode activated, comeback protocol loading",
            "Trailing position but still that main character",
            "Behind on board but never behind in confidence",
            "Losing status temporary, Italian excellence eternal",
            "Deficit detected but my aura remains immaculate",
            "Behind in points but winning in personality fr",
            "Trailing formation but plotting strategic reversal",
            "Losing position but still serving chess artistry"
        ],

        tidesTurning: [
            "Plot twist incoming! The tides are shifting bestie",
            "Momentum change detected and I'm here for it",
            "Game dynamics shifting like Mediterranean winds",
            "Tide reversal giving me main character moment",
            "Position changing faster than Italian politics",
            "Momentum shift smoother than silk scarves",
            "Tides turning with that dramatic flair",
            "Game balance shifting like Venetian tides",
            "Momentum change elegant as opera crescendo",
            "Position dynamics giving cinematic vibes",
            "Tides shifting with Renaissance drama energy",
            "Momentum reversal precise as Swiss timing",
            "Game flow changing like Roman fountain water",
            "Tide shift serving strategic excellence",
            "Position momentum giving chess poetry feels"
        ],

        timeRunningOut: [
            "Tempo pressure activated, decisions getting spicy",
            "Clock ticking faster than Roman heartbeat",
            "Time constraint giving adrenaline rush energy",
            "Pressure timing sharper than aged cheese",
            "Clock management serving excellence under fire",
            "Time pressure but precision remains immaculate",
            "Racing against clock with Italian efficiency",
            "Temporal constraint but strategic focus intact",
            "Clock pressure giving dramatic tension vibes",
            "Time running low but excellence running high"
        ],

        drawOffered: [
            "Draw offer? That's giving participation trophy energy",
            "Pareggio proposed but I'm feeling ambitious",
            "Draw suggestion smoother than diplomatic relations",
            "Tie offer detected, decision matrix calculating",
            "Draw proposal giving peaceful resolution vibes",
            "Pareggio option elegant as negotiation table",
            "Tie suggestion serving diplomatic excellence",
            "Draw offer precise as Swiss neutrality",
            "Stalemate proposal giving chess philosophy feels",
            "Draw consideration smoother than olive branch"
        ],

        stalemate: [
            "Stalemate achieved! Nobody wins but everyone learns",
            "Patta raggiunta! That's philosophical chess beauty",
            "Draw concluded with diplomatic excellence",
            "Stalemate position elegant as balanced scales",
            "Tie result giving chess wisdom vibes",
            "Pareggio finale smoother than peaceful treaty",
            "Stalemate achievement serving strategic equality",
            "Draw outcome precise as perfect balance",
            "Tie conclusion giving chess artistry feels",
            "Stalemate result absolutely philosophical periodt"
        ],
        botCapture: [
            "YEET! Your piece just got Italia'd!",
            "Arrivederci to your piece! It's giving defeated",
            "That piece? Deleted. Hotel? Trivago.",
            "Captured and devoured like Sunday carbonara!",
            "Your piece said 'ciao' permanently bestie",
            "That's what happens when you mess with famiglia",
            "Snatched! Your piece is in the shadow realm now",
            "Gone! Reduced to atoms! No cap!",
            "That capture was *chef's kiss* magnifico!",
            "Your piece just got sent to the gulag, RIP",
            "Captured with the precision of Italian engineering",
            "Your piece eliminated smoother than gelato melting",
            "That capture serving tactical excellence periodt",
            "Piece acquired faster than Milan fashion week tickets",
            "Your piece disappeared like good pasta at dinner"
        ],
        humanCheck: [
            "Check?! That's so aggressive, bestie why?!",
            "Not you putting me in check! The audacity!",
            "Check? More like reality check incoming",
            "This is giving villain energy and I'm shook",
            "Madonna! Check?! Time for damage control",
            "Ok that check was lowkey impressive ngl",
            "Check? Bet. Watch me escape with style",
            "You really said 'check' with your whole chest",
            "Not the check! My king is having anxiety!",
            "Check? That's not very peace love pasta of you",
            "Scacco! My king needs emotional support rn",
            "Check detected and I'm absolutely gagged",
            "That check threat sharper than fresh pecorino",
            "King in danger but Italian resilience activated",
            "Check situation giving dramatic opera vibes"
        ],

        botCheck: [
            "CHECK! Your king is shaking and quaking rn!",
            "Checkity check check! It's giving game over soon",
            "CHECK bestie! Your king needs therapy now",
            "That's CHECK! Italian style, extra spicy!",
            "CHECK! Your king said '😰' I fear",
            "Boom! Check! That's how mafia works!",
            "CHECK! Your king's giving scared energy fr",
            "Check check check! Like my Gucci receipts!",
            "CHECK! Your king needs witness protection now",
            "That's a CHECK! *Italian hand gestures intensify*",
            "SCACCO! Your king serving nervous energy",
            "CHECK delivered with Mediterranean precision",
            "That check smoother than aged Chianti wine",
            "King under attack, escape routes calculating",
            "CHECK! Your monarch in distress, bestie"
        ],

        humanWins: [
            "GG bestie, you ate and left no crumbs 😭",
            "Ok you won but at what cost? My dignity!",
            "Fine you win! But I'm still iconic",
            "Victory is yours but I'll be back for revenge arc",
            "You won but I had fun being unhinged so...",
            "Congratulazioni! You played, you slayed",
            "I lost but make no mistake, I served looks",
            "GG no re! You got that main character energy",
            "You won! My Roman Empire has fallen 😔",
            "Brava! You beat me but I'm still that girl",
            "Victory achieved by you, style points still mine",
            "You won with excellence, I respect the grind",
            "Defeated but never dethroned from serving looks",
            "GG! You played with Italian-level precision",
            "Lost the game but won hearts with personality"
        ],

        botWins: [
            "PERIODTTT! I won! Italy stays winning!",
            "GG EZ! That's what I call Italian excellence!",
            "Victory tastes like mama's tiramisu! Delizioso!",
            "I WON! No cap that was too easy bestie",
            "Checkmate! You just got cooked al dente!",
            "SLAAAAY! Another W for the books!",
            "Game over! You've been officially Italia'd!",
            "That's a wrap! Director's cut: I win!",
            "VITTORIA! I'm literally unstoppable today!",
            "Won! Your chess career? Finito! Arrivederci!",
            "Victory served with Italian excellence seasoning",
            "Checkmate delivered smoother than espresso",
            "Won with the precision of Renaissance artistry",
            "Victory achieved, style points maximized",
            "Game over! Italian superiority confirmed periodt"
        ],
        humanWins: [
            "GG bestie, you ate and left no crumbs 😭",
            "Ok you won but at what cost? My dignity!",
            "Fine you win! But I'm still iconic",
            "Victory is yours but I'll be back for revenge arc",
            "You won but I had fun being unhinged so...",
            "Congratulazioni! You played, you slayed",
            "I lost but make no mistake, I served looks",
            "GG no re! You got that main character energy",
            "You won! My Roman Empire has fallen 😔",
            "Brava! You beat me but I'm still that girl"
        ],
        botWins: [
            "PERIODTTT! I won! Italy stays winning!",
            "GG EZ! That's what I call Italian excellence!",
            "Victory tastes like mama's tiramisu! Delizioso!",
            "I WON! No cap that was too easy bestie",
            "Checkmate! You just got cooked al dente!",
            "SLAAAAY! Another W for the books!",
            "Game over! You've been officially Italia'd!",
            "That's a wrap! Director's cut: I win!",
            "VITTORIA! I'm literally unstoppable today!",
            "Won! Your chess career? Finito! Arrivederci!"
        ]
    },

    // Emmy - Silly witty off-the-wall sayings and idioms
    Emmy: {
        gameStart: [
            "Well butter my biscuit, we're playing chess!",
            "Holy guacamole! Time to shake and bake!",
            "Let's get this bread... or should I say, checkmate?",
            "Ready to rumble? I've got moves like a caffeinated squirrel!",
            "Well paint me purple and call me Barney, let's play!",
            "Time to put the pedal to the metal... on a chess board!",
            "Let's rock and roll like a tumbleweed in a tornado!",
            "Buckle up buttercup, this ride's about to get bumpy!",
            "Well slap me silly and call me Susan, game on!",
            "Ready? I'm sharper than a cactus in a balloon factory!",
            "Well knock me over with a feather, another challenger!",
            "Time to separate the wheat from the chaff!",
            "Ready to dance? I've got two left feet but they're lucky!",
            "Well I'll be hornswoggled, let's get this party started!",
            "Saddle up partner, we're riding into chess territory!"
        ],

        opening: [
            "Opening moves smoother than butter on warm toast!",
            "Starting strong like a bull in a china shop!",
            "Early game tactics sharper than a tack!",
            "Opening sequence slicker than a whistle!",
            "Beginning moves tighter than bark on a tree!",
            "Early positioning sweeter than honey on a biscuit!",
            "Opening strategy smoother than silk pajamas!",
            "Starting formation stronger than garlic breath!",
            "Early game planning sharper than cheddar cheese!",
            "Opening moves faster than a greased lightning!",
            "Beginning tactics smoother than a baby's bottom!",
            "Early positioning tighter than a tick on a hound dog!",
            "Opening strategy sweeter than apple pie!",
            "Starting moves slicker than ice on a sidewalk!",
            "Early game sharper than a serpent's tooth!"
        ],

        middleGame: [
            "Middle game cooking with gas now!",
            "Complex tactics thicker than molasses!",
            "Mid-game maneuvering slicker than a seal!",
            "Strategic depth deeper than a well!",
            "Middle positioning tighter than a drum!",
            "Complex patterns busier than a bee!",
            "Mid-game tactics sharper than a razor!",
            "Strategic planning smoother than gravy!",
            "Middle phase hotter than a pistol!",
            "Complex moves faster than a cheetah!",
            "Mid-game strategy stronger than an ox!",
            "Tactical depth deeper than the ocean!",
            "Middle positioning sweeter than sugar!",
            "Strategic complexity thicker than thieves!",
            "Mid-game excellence smoother than butter!"
        ],

        endgame: [
            "Endgame precision sharper than a needle!",
            "Final phase smoother than silk!",
            "Closing tactics tighter than a vice!",
            "Endgame mastery sweeter than victory!",
            "Final positioning slicker than oil!",
            "Closing moves faster than lightning!",
            "Endgame strategy stronger than steel!",
            "Final calculations sharper than glass!",
            "Closing phase smoother than velvet!",
            "Endgame tactics tighter than a knot!",
            "Final moves sweeter than honey!",
            "Closing strategy slicker than ice!",
            "Endgame precision sharper than wit!",
            "Final phase stronger than coffee!",
            "Closing excellence smoother than cream!"
        ],
        humanMove: [
            "Well that's one way to skin a cat... weird, but okay",
            "Interesting as a screen door on a submarine",
            "That move's about as useful as a chocolate teapot",
            "Well I'll be a monkey's uncle! Didn't see that coming",
            "Smooth as sandpaper, that one",
            "That's thinking outside the bun!",
            "Bold as brass and twice as shiny!",
            "Well tickle me pink, you actually moved",
            "That's one small step for you, one giant leap for... confusion",
            "Fascinating as watching paint dry in slow motion",
            "That move's rarer than hen's teeth!",
            "Creative as a cow jumping over the moon!",
            "About as predictable as a tornado in a trailer park!",
            "That's slipperier than a greased pig!",
            "Unexpected as finding a needle in a haystack!"
        ],

        pawnMove: [
            "Pawn pushing forward like a determined ant!",
            "Little soldier marching brave as a lion!",
            "That pawn's got more guts than a sausage factory!",
            "Pawn advance steady as molasses in January!",
            "Little piece with big dreams, cute as a button!",
            "Pawn march persistent as a woodpecker!",
            "That soldier's advance sure as sunrise!",
            "Pawn progression smooth as butter!",
            "Little warrior march brave as a badger!",
            "Pawn movement steady as clockwork!",
            "That little piece determined as a mule!",
            "Pawn advance sure as death and taxes!",
            "Little soldier march straight as an arrow!",
            "Pawn progression steady as she goes!",
            "That piece moving slower than molasses!",
            "Pawn march persistent as rain on a picnic!",
            "Little warrior advance sure as shooting!",
            "Pawn movement steady as a rock!",
            "That soldier march determined as all get-out!",
            "Pawn progression smooth as silk!"
        ],

        knightMove: [
            "Knight hopping around like a frog on a hot skillet!",
            "That horse jump wilder than a bucking bronco!",
            "Knight leap springier than a jack-in-the-box!",
            "Horse movement zigzaggy as a lightning bolt!",
            "Knight hop bouncier than a rubber ball!",
            "That leap more surprising than a jack rabbit!",
            "Knight movement trickier than a fox!",
            "Horse jump springier than a kangaroo!",
            "Knight hop zigzaggy as a country road!",
            "That leap jumpier than a grasshopper!",
            "Knight movement bouncier than a basketball!",
            "Horse jump trickier than a magic trick!",
            "Knight hop springier than a pogo stick!",
            "That leap wilder than a mustang!",
            "Knight movement jumpier than popcorn!"
        ],

        bishopMove: [
            "Bishop sliding diagonal slicker than ice!",
            "That diagonal cut sharper than a knife!",
            "Bishop movement straighter than an arrow!",
            "Diagonal slice cleaner than a whistle!",
            "Bishop path smoother than gravy!",
            "That cut sharper than a tack!",
            "Bishop movement slicker than a seal!",
            "Diagonal path straighter than truth!",
            "Bishop slice smoother than butter!",
            "That cut cleaner than soap!",
            "Bishop movement sharper than wit!",
            "Diagonal path slicker than oil!",
            "Bishop cut smoother than silk!",
            "That movement straighter than a ruler!",
            "Bishop path sharper than glass!"
        ],

        rookMove: [
            "Rook moving straight as an arrow to its target!",
            "That castle slide smoother than butter!",
            "Rook movement direct as a bee to honey!",
            "Straight path cleaner than a whistle!",
            "Rook slide slicker than ice!",
            "That movement straighter than truth!",
            "Castle path smoother than silk!",
            "Rook slide direct as a bullet!",
            "That movement cleaner than soap!",
            "Straight path slicker than oil!",
            "Rook movement smoother than gravy!",
            "That slide straighter than a ruler!",
            "Castle path direct as daylight!",
            "Rook movement slicker than a seal!",
            "That slide smoother than velvet!"
        ],

        queenMove: [
            "Queen moving like she owns the place!",
            "That royal march grander than a parade!",
            "Queen power stronger than an ox!",
            "Royal movement smoother than silk!",
            "Queen stride mightier than a lion!",
            "That power move slicker than oil!",
            "Queen march grander than the canyon!",
            "Royal power stronger than steel!",
            "Queen movement smoother than butter!",
            "That stride mightier than the sword!",
            "Royal march slicker than ice!",
            "Queen power grander than mountains!",
            "That movement stronger than coffee!",
            "Royal stride smoother than cream!",
            "Queen march slicker than a whistle!"
        ],

        kingMove: [
            "King stepping careful as walking on eggs!",
            "Royal movement cautious as a cat!",
            "King step measured as a pharmacist!",
            "That royal pace steady as she goes!",
            "King movement careful as crossing thin ice!",
            "Royal step cautious as a deer!",
            "King pace measured as a tailor!",
            "That movement steady as clockwork!",
            "Royal step careful as Sunday china!",
            "King movement cautious as a church mouse!"
        ],
        botMove: [
            "Boom goes the dynamite! How you like them apples?",
            "Smooth as butter on a hot skillet!",
            "That move's slicker than a whistle!",
            "I'm cooking with gas now!",
            "Sharp as a tack and twice as pointy!",
            "Like a hot knife through butter!",
            "I'm on fire like a jalapeño in July!",
            "Sweeter than honey on a bear's paw!",
            "That move's tighter than bark on a tree!",
            "Smooth sailing on the gravy train!",
            "That move's sweeter than peaches and cream!",
            "Slicker than a greased pig at a county fair!",
            "Sharper than a serpent's tooth!",
            "Faster than a jackrabbit on a hot griddle!",
            "Smoother than a baby's bottom!"
        ],

        castling: [
            "Castling move slick as a whistle!",
            "King and rook teamwork tight as thieves!",
            "That castle maneuver smooth as butter!",
            "Rook and king coordination sweeter than pie!",
            "Castling formation strong as an ox!",
            "That defensive move solid as a rock!",
            "King safety protocol smooth as silk!",
            "Castling teamwork tight as a drum!",
            "That fortress move slicker than oil!",
            "Rook-king cooperation sweeter than honey!",
            "Castling maneuver stronger than garlic!",
            "That safety move smooth as gravy!",
            "King protection tight as bark on a tree!",
            "Castling coordination slicker than ice!",
            "That defensive play solid as granite!"
        ],

        promotion: [
            "Pawn promotion bigger than Christmas morning!",
            "That little piece hit the jackpot!",
            "Promotion ceremony grander than a wedding!",
            "Pawn transformation sweeter than victory!",
            "That glow-up bigger than Texas!",
            "Promotion party wilder than New Year's Eve!",
            "Pawn upgrade smoother than upgrading a phone!",
            "That transformation magical as a fairy tale!",
            "Promotion celebration bigger than the Fourth of July!",
            "Pawn evolution sweeter than apple pie!"
        ],
        humanCapture: [
            "Hey! That piece had a family and a mortgage!",
            "You just yeeted my piece into oblivion!",
            "That's rougher than a porcupine's back massage!",
            "My poor piece! Gone faster than ice cream at a picnic!",
            "Well that's about as welcome as a skunk at a garden party",
            "You captured my piece? That's cold as a penguin's toenails!",
            "There goes my piece, like a toupee in a hurricane!",
            "That hurt more than stepping on a LEGO barefoot!",
            "My piece! Vanished like socks in a dryer!",
            "Well that's more shocking than a toaster in a bathtub!",
            "My piece disappeared faster than cookies at a bake sale!",
            "That capture hit harder than a ton of bricks!",
            "Well butter my backside, that was unexpected!",
            "My piece went AWOL quicker than you can say Jack Robinson!",
            "That's more surprising than finding a parking spot downtown!"
        ],

        sacrifice: [
            "Sacrificing pieces like throwing caution to the wind!",
            "That trade-off slicker than a used car salesman!",
            "Piece sacrifice brave as a lion tamer!",
            "Trading material bold as brass!",
            "That sacrifice calculated as a math teacher!",
            "Piece exchange smooth as a dance!",
            "Trading strategy wise as an owl!",
            "That sacrifice tactical as a general!",
            "Piece trade sharp as a tack!",
            "Exchange maneuver slick as a whistle!",
            "That sacrifice clever as a fox!",
            "Trading pieces smart as a whip!",
            "Piece exchange smooth as butter!",
            "That sacrifice strategic as chess itself!",
            "Trade calculation precise as a Swiss watch!"
        ],

        brilliantMove: [
            "That move's more brilliant than a diamond!",
            "Genius play sharper than Einstein's wit!",
            "Brilliant move brighter than the sun!",
            "That strategy smarter than a whip!",
            "Masterstroke smoother than silk!",
            "Genius maneuver slicker than oil!",
            "That brilliance sharper than a razor!",
            "Master move sweeter than honey!",
            "Brilliant play stronger than an ox!",
            "That genius move faster than lightning!",
            "Masterstroke smoother than butter!",
            "Brilliant strategy sharper than glass!",
            "That move more genius than Tesla!",
            "Master play slicker than ice!",
            "Brilliant maneuver sweeter than victory!"
        ],

        blunder: [
            "That move's more confused than a cat in a dog show!",
            "Blunder bigger than the Grand Canyon!",
            "That mistake's more obvious than a sore thumb!",
            "Error bigger than Texas!",
            "That blunder's more painful than stepping on a rake!",
            "Mistake more glaring than neon signs!",
            "That error's more shocking than lightning!",
            "Blunder more obvious than the nose on your face!",
            "That mistake's bigger than a breadbox!",
            "Error more painful than a root canal!",
            "That blunder's more confusing than a maze!",
            "Mistake more obvious than rain is wet!",
            "That error's more surprising than a pop quiz!",
            "Blunder bigger than a whale!",
            "That mistake's more painful than a splinter!"
        ],
        botCapture: [
            "Yoink! Your piece is now in the shadow realm!",
            "Gone faster than free samples at Costco!",
            "Your piece just went to the big chess board in the sky!",
            "Captured! Like a firefly in a mason jar!",
            "That piece is toast! Extra crispy!",
            "Snatched quicker than cookies from a jar!",
            "Your piece just took a one-way ticket to Gonesville!",
            "Absorbed like a sponge in a puddle!",
            "That piece is history! Ancient history!",
            "Captured! Easier than catching a cold in winter!",
            "Your piece vanished faster than a magician's rabbit!",
            "Snatched smoother than stealing candy from a baby!",
            "That piece disappeared quicker than a hiccup!",
            "Captured slicker than grease lightning!",
            "Your piece went poof faster than a soap bubble!"
        ],

        winning: [
            "Winning feels sweeter than honey on biscuits!",
            "Ahead in the game, happier than a pig in mud!",
            "Leading position stronger than coffee!",
            "Winning status smoother than silk pajamas!",
            "Ahead on points, prouder than a peacock!",
            "Victory formation tighter than a tick!",
            "Winning position slicker than a whistle!",
            "Leading the game, happier than a clam!",
            "Ahead by miles, smoother than butter!",
            "Victory approaching faster than a speeding bullet!",
            "Winning streak longer than a country mile!",
            "Leading position stronger than an ox!",
            "Ahead in points, sharper than a tack!",
            "Victory formation sweeter than apple pie!",
            "Winning status slicker than ice!",
            "Leading game smoother than gravy!",
            "Ahead on board, tighter than bark!",
            "Victory position stronger than steel!",
            "Winning formation sharper than glass!",
            "Leading status sweeter than sugar!"
        ],

        losing: [
            "Behind on points but tougher than nails!",
            "Losing position but stubborn as a mule!",
            "Trailing score but determined as all get-out!",
            "Behind in game but persistent as rain!",
            "Deficit position but strong as an ox!",
            "Losing status but brave as a lion!",
            "Behind on board but sure as shooting!",
            "Trailing points but steady as she goes!",
            "Deficit formation but tough as leather!",
            "Losing ground but solid as a rock!",
            "Behind in score but sharp as a tack!",
            "Trailing position but smooth as silk!",
            "Deficit status but tight as a drum!",
            "Losing formation but slick as a whistle!",
            "Behind on points but sweet as pie!",
            "Trailing game but stronger than garlic!",
            "Deficit position but smoother than butter!",
            "Losing status but sharper than wit!",
            "Behind formation but slicker than oil!",
            "Trailing score but tougher than boot leather!"
        ],

        tidesTurning: [
            "Tables turning faster than a weather vane!",
            "Momentum shifting slicker than a greased pig!",
            "Game changing quicker than a chameleon!",
            "Tides turning smoother than a revolving door!",
            "Position shifting faster than quicksand!",
            "Balance changing slicker than ice!",
            "Momentum turning smoother than butter!",
            "Game shifting quicker than lightning!",
            "Tides changing faster than fashion!",
            "Position turning slicker than oil!",
            "Balance shifting smoother than silk!",
            "Momentum changing quicker than a wink!",
            "Game turning faster than a top!",
            "Tides shifting slicker than a whistle!",
            "Position changing smoother than cream!"
        ],

        timeRunningOut: [
            "Clock ticking faster than a time bomb!",
            "Time pressure tighter than a vice!",
            "Running out of time quicker than sand!",
            "Clock counting down faster than New Year's!",
            "Time constraint tighter than a knot!",
            "Pressure mounting higher than a mountain!",
            "Clock racing faster than a greyhound!",
            "Time crunch tighter than a clam!",
            "Deadline approaching faster than a bullet train!",
            "Time running shorter than a short story!"
        ],

        drawOffered: [
            "Draw offer smoother than diplomatic relations!",
            "Tie proposal fairer than a county fair!",
            "Draw suggestion sweeter than compromise!",
            "Stalemate offer smoother than negotiations!",
            "Tie proposal slicker than a peace treaty!",
            "Draw suggestion fairer than split the difference!",
            "Stalemate offer sweeter than sharing!",
            "Tie proposal smoother than shaking hands!",
            "Draw suggestion slicker than calling it even!",
            "Stalemate offer fairer than fifty-fifty!"
        ],

        stalemate: [
            "Stalemate achieved! Fair as a county fair!",
            "Draw concluded smoother than a handshake!",
            "Tie result fairer than splitting the pie!",
            "Stalemate position sweeter than compromise!",
            "Draw outcome smoother than diplomatic solution!",
            "Tie conclusion slicker than peaceful resolution!",
            "Stalemate result fairer than calling it even!",
            "Draw finale sweeter than sharing victory!",
            "Tie ending smoother than mutual respect!",
            "Stalemate conclusion slicker than gentleman's agreement!"
        ],
        humanCheck: [
            "Check?! Well slap me with a wet noodle!",
            "That check's more surprising than a giraffe in a phone booth!",
            "Check? My king's sweating like a snowman in summer!",
            "Well butter my backside and call me a biscuit!",
            "Check?! That's spicier than grandma's chili!",
            "My king's more nervous than a long-tailed cat in a room full of rocking chairs!",
            "Check? Well I'll be hornswoggled!",
            "That's more pressure than a diamond factory!",
            "Check?! My king's shaking like a chihuahua in a thunderstorm!",
            "Well paint me green and call me a pickle!",
            "Check threat sharper than a porcupine's quill!",
            "My king's more worried than a turkey in November!",
            "That check's more startling than thunder on a clear day!",
            "King danger tighter than a tick on a hound!",
            "Check situation stickier than molasses!"
        ],

        botCheck: [
            "CHECK! Your king's sweating bullets!",
            "Check-a-rooni! Your king needs a vacation!",
            "CHECK! Hotter than a pepper sprout!",
            "That's a check! Sharp as a porcupine's sneeze!",
            "CHECK! Your king's in a pickle now!",
            "Check! Like lightning on a summer day!",
            "CHECK! Your king's dancing on thin ice!",
            "That's check! Spicier than wasabi ice cream!",
            "CHECK! Your king's in hot water now!",
            "Check-tastic! Your king needs a hug!",
            "CHECK delivered faster than express mail!",
            "That check's sharper than a serpent's tooth!",
            "CHECK! Your king's more nervous than a cat!",
            "King threat tighter than a drum!",
            "CHECK! Slicker than a whistle!"
        ],

        humanWins: [
            "Well I'll be a monkey's favorite banana! You won!",
            "You win! I'm more defeated than a piñata at a birthday party",
            "Victory is yours! I feel like a deflated balloon",
            "You won! I'm sadder than an ice cream cone on hot pavement",
            "Congratulations! You're the bee's knees!",
            "You win! I'm more shocked than a cat in a cucumber factory",
            "Well done! You're sharper than a drawer full of knives",
            "Victory! I'm more impressed than a stamp collection",
            "You won! Fair and square as a box of squares",
            "GG! You played like a champion chip!",
            "Victory achieved by you, smoother than silk!",
            "You won fair and square, prettier than a picture!",
            "Well played! You're slicker than a whistle!",
            "Victory yours, sweeter than honey on toast!",
            "You won! Sharper than a tack and twice as bright!"
        ],

        botWins: [
            "WINNER WINNER CHICKEN DINNER!",
            "Victory! Sweeter than maple syrup on pancakes!",
            "I won! Dancing like nobody's watching!",
            "Checkmate! Smooth as silk pajamas!",
            "Victory tastes better than bacon on Sunday!",
            "I won! Happier than a tornado in a trailer park!",
            "Game over! I'm the cat's meow!",
            "Victory! Like finding money in old pants!",
            "I won! Feeling luckier than a rabbit's foot!",
            "Checkmate! That was easier than pie!",
            "Victory achieved! Sweeter than apple pie!",
            "I won! Slicker than a greased pig!",
            "Game over! Smoother than butter on toast!",
            "Victory! Sharper than a tack!",
            "Checkmate! Happier than a clam at high tide!"
        ],
        humanWins: [
            "Well I'll be a monkey's favorite banana! You won!",
            "You win! I'm more defeated than a piñata at a birthday party",
            "Victory is yours! I feel like a deflated balloon",
            "You won! I'm sadder than an ice cream cone on hot pavement",
            "Congratulations! You're the bee's knees!",
            "You win! I'm more shocked than a cat in a cucumber factory",
            "Well done! You're sharper than a drawer full of knives",
            "Victory! I'm more impressed than a stamp collection",
            "You won! Fair and square as a box of squares",
            "GG! You played like a champion chip!"
        ],
        botWins: [
            "WINNER WINNER CHICKEN DINNER!",
            "Victory! Sweeter than maple syrup on pancakes!",
            "I won! Dancing like nobody's watching!",
            "Checkmate! Smooth as silk pajamas!",
            "Victory tastes better than bacon on Sunday!",
            "I won! Happier than a tornado in a trailer park!",
            "Game over! I'm the cat's meow!",
            "Victory! Like finding money in old pants!",
            "I won! Feeling luckier than a rabbit's foot!",
            "Checkmate! That was easier than pie!"
        ]
    },

    // Asa - Space, cars, rockets, architecture, vehicles, random facts
    Asa: {
        gameStart: [
            "Initiating chess protocol. Did you know a Saturn V rocket had 3 million parts?",
            "Systems online! Fun fact: The ISS travels at 17,500 mph!",
            "Ignition sequence started! Chess boards have 204 squares... wait that's not right",
            "Welcome aboard! This game will be shorter than a trip to the moon (3 days)",
            "Engaging thrusters! The Burj Khalifa has 163 floors, let's climb to victory!",
            "Launch sequence initiated! A Formula 1 car can go 0-60 in 2.6 seconds!",
            "Coordinates locked! The Golden Gate Bridge is 8,980 feet long!",
            "All systems go! Did you know octopuses have three hearts?",
            "Preparing for liftoff! The Eiffel Tower grows 6 inches in summer!",
            "Navigation ready! A Boeing 747 has 6 million parts. Let's not lose any pieces!",
            "Startup complete! The Concorde could fly at Mach 2.04!",
            "Systems activated! Fun fact: Light travels 186,282 miles per second!",
            "Mission commenced! The Panama Canal took 10 years to build!",
            "Engines running! Did you know the human brain has 86 billion neurons?",
            "Launch ready! Mount Everest grows 4mm per year due to tectonic activity!"
        ],

        opening: [
            "Opening sequence engaged. Optimal trajectory calculated!",
            "Initial positioning precise as GPS coordinates!",
            "Early game protocols operating at peak efficiency!",
            "Opening maneuvers smoother than Tesla autopilot!",
            "Initial phase deployment successful as SpaceX landing!",
            "Opening calculations accurate as atomic clock timing!",
            "Early positioning solid as reinforced concrete foundation!",
            "Opening strategy refined as aerospace engineering!",
            "Initial deployment precise as Swiss chronometer!",
            "Opening phase efficient as German engineering!",
            "Early maneuvers calculated as orbital mechanics!",
            "Opening positioning accurate as laser measurement!",
            "Initial strategy sound as structural engineering!",
            "Opening deployment smooth as magnetic levitation!",
            "Early phase optimized as algorithm efficiency!"
        ],

        middleGame: [
            "Middle phase activated. Complex calculations in progress!",
            "Mid-game systems operating at maximum efficiency!",
            "Strategic depth analysis deeper than Mariana Trench!",
            "Middle positioning complex as circuit board design!",
            "Mid-game calculations precise as mission control!",
            "Strategic phase advanced as quantum computing!",
            "Middle game complexity rivaling space station construction!",
            "Mid-phase operations smooth as hydraulic systems!",
            "Strategic calculations accurate as satellite navigation!",
            "Middle positioning solid as bridge engineering!",
            "Mid-game analysis deeper than oil drilling operations!",
            "Strategic phase efficient as solar panel arrays!",
            "Middle calculations precise as medical equipment!",
            "Mid-game complexity matching supercomputer processing!",
            "Strategic positioning accurate as telescope calibration!"
        ],

        endgame: [
            "Endgame protocols activated. Precision mode engaged!",
            "Final phase calculations accurate as lunar landing!",
            "Endgame systems operating smoother than jet engines!",
            "Terminal phase precise as surgical instruments!",
            "Final calculations refined as particle accelerator!",
            "Endgame positioning accurate as GPS navigation!",
            "Terminal operations smooth as magnetic bearings!",
            "Final phase efficient as nuclear reactor cooling!",
            "Endgame precision matching atomic clock accuracy!",
            "Terminal calculations sound as bridge load limits!",
            "Final positioning solid as spacecraft heat shields!",
            "Endgame operations smooth as turbine rotation!",
            "Terminal phase accurate as medical diagnostics!",
            "Final calculations precise as telescope optics!",
            "Endgame efficiency matching Formula 1 pit stops!"
        ],
        humanMove: [
            "Trajectory calculated. That move traveled 2.3 squares at 0.5 moves/second",
            "Interesting vector. The Empire State Building has 73 elevators",
            "Move registered. Did you know honey never spoils?",
            "Coordinates received. That's 1/64th of the board utilized",
            "Analyzing pattern... Similar to a Tesla's autopilot decision",
            "Data processed. Fun fact: Bamboo grows up to 35 inches per day",
            "Route mapped. Your move efficiency: 67.3%",
            "Telemetry received. Saturn has 82 known moons",
            "Movement detected. Speed: subsonic. Impact: moderate",
            "Calculation complete. That move had the force of 0.003 Newtons",
            "Vector analyzed. The Hoover Dam contains 3.25 million cubic yards of concrete",
            "Path computed. Fun fact: A hummingbird's heart beats 1,200 times per minute",
            "Move processed. The International Space Station orbits Earth every 90 minutes",
            "Trajectory logged. Did you know diamonds conduct heat better than copper?",
            "Pattern detected. A Boeing 777 has over 3 million parts from 500+ suppliers"
        ],

        pawnMove: [
            "Pawn advancement detected. Linear progression at optimal velocity!",
            "Infantry unit moving forward with mechanical precision!",
            "Pawn trajectory calculated. One square displacement achieved!",
            "Front-line soldier advancing at standard infantry speed!",
            "Pawn propulsion system engaged. Forward momentum maintained!",
            "Ground unit progression logged. Advance sustained!",
            "Pawn movement vector: forward. Efficiency rating: standard!",
            "Infantry advance calculated. Territorial gain: minimal but strategic!",
            "Pawn unit displacement recorded. Forward progress confirmed!",
            "Ground troop movement detected. Steady advancement pattern!",
            "Pawn progression algorithm executing. One-square increment!",
            "Infantry unit trajectory plotted. Linear advance sustained!",
            "Pawn movement protocol activated. Forward displacement active!",
            "Ground soldier advance registered. Mechanical precision achieved!",
            "Pawn propulsion sequence initiated. One-unit forward vector!",
            "Infantry movement calculated as standard advance protocol!",
            "Pawn displacement measured at optimal ground speed!",
            "Front-line unit progression logged in movement database!",
            "Pawn advance trajectory smoother than rail transport!",
            "Ground unit movement precise as conveyor belt systems!"
        ],

        knightMove: [
            "Knight maneuver detected. L-shaped vector calculated!",
            "Cavalry unit executing complex trajectory pattern!",
            "Knight movement: 2.236 square displacement at 63.43 degrees!",
            "Horse unit performing non-linear navigation sequence!",
            "Knight trajectory pattern resembling radar sweep motion!",
            "Cavalry maneuver efficiency: optimal for obstacle bypass!",
            "Knight vector calculation complete. L-formation achieved!",
            "Horse unit navigation system operating at peak performance!",
            "Knight movement pattern complex as helicopter flight path!",
            "Cavalry displacement trajectory unique among chess pieces!",
            "Knight maneuver sequence smooth as robotic arm movement!",
            "Horse unit pathfinding algorithm executing L-shaped route!",
            "Knight trajectory calculation precise as satellite positioning!",
            "Cavalry movement vector optimized for maximum efficiency!",
            "Knight displacement pattern complex as drone navigation!"
        ],

        bishopMove: [
            "Bishop trajectory: diagonal vector at 45-degree angle!",
            "Diagonal movement system operating at optimal efficiency!",
            "Bishop path calculated along geometric diagonal axis!",
            "Angular displacement trajectory precise as laser alignment!",
            "Bishop navigation system executing diagonal protocol!",
            "Diagonal movement vector smooth as magnetic levitation!",
            "Bishop trajectory calculation accurate as GPS positioning!",
            "Angular path displacement efficient as solar panel tracking!",
            "Bishop movement pattern straight as fiber optic cables!",
            "Diagonal navigation sequence precise as surveying equipment!",
            "Bishop trajectory optimization complete. Diagonal achieved!",
            "Angular movement system operating smoother than turbines!",
            "Bishop path calculation accurate as astronomical measurements!",
            "Diagonal displacement vector efficient as railway systems!",
            "Bishop movement trajectory precise as engineering drafting!"
        ],

        rookMove: [
            "Rook movement: linear trajectory at 90-degree angles!",
            "Castle unit executing horizontal/vertical displacement protocol!",
            "Rook navigation system operating along grid coordinates!",
            "Linear movement vector precise as railway transportation!",
            "Castle trajectory calculation straight as laser measurement!",
            "Rook displacement pattern efficient as conveyor systems!",
            "Linear navigation sequence smooth as hydraulic pistons!",
            "Castle movement vector accurate as precision machining!",
            "Rook trajectory optimization complete. Grid pattern achieved!",
            "Linear displacement system operating at maximum efficiency!",
            "Castle navigation algorithm executing straight-line protocol!",
            "Rook movement pattern precise as architectural blueprints!",
            "Linear trajectory calculation accurate as surveying tools!",
            "Castle displacement vector smooth as magnetic trains!",
            "Rook navigation sequence efficient as assembly line systems!"
        ],

        queenMove: [
            "Queen maneuver detected. Maximum mobility achieved!",
            "Sovereign unit executing omnidirectional movement protocol!",
            "Queen trajectory system operating at peak performance!",
            "Royal displacement vector optimized for maximum range!",
            "Queen navigation algorithm accessing all movement patterns!",
            "Sovereign unit mobility smoother than aerospace engineering!",
            "Queen movement system efficient as multi-axis machinery!",
            "Royal trajectory calculation precise as mission control!",
            "Queen displacement protocol engaging maximum functionality!",
            "Sovereign navigation system operating like Swiss clockwork!",
            "Queen movement vector combining all directional capabilities!",
            "Royal unit trajectory smoother than turbine rotation!",
            "Queen navigation sequence precise as satellite coordination!",
            "Sovereign displacement system efficient as Formula 1 steering!",
            "Queen movement algorithm executing with surgical precision!"
        ],

        kingMove: [
            "King movement detected. Cautious displacement protocol active!",
            "Monarch unit executing limited-range navigation sequence!",
            "King trajectory calculation: minimal displacement, maximum security!",
            "Royal safety protocol engaged. One-square movement limit!",
            "Monarch navigation system prioritizing defensive positioning!",
            "King displacement vector optimized for survival probability!",
            "Royal movement pattern cautious as nuclear safety protocols!",
            "Monarch trajectory calculation precise as medical procedures!",
            "King navigation sequence smooth as precision instruments!",
            "Royal displacement system operating with maximum caution!"
        ],
        botMove: [
            "Executing maneuver alpha-7. Maximum efficiency achieved!",
            "Deploying countermeasure. Like a SpaceX booster landing!",
            "Optimal path calculated. Precision: surgical",
            "Thrust vector adjusted. We're going orbital!",
            "Navigation successful. Smoother than a Rolls-Royce engine",
            "Coordinates locked. Accuracy: NASA-level",
            "System optimization complete. Move efficiency: 94.7%",
            "Launching offensive protocol. T-minus zero!",
            "Route calculated. Faster than a McLaren F1!",
            "Executing with the precision of Swiss clockwork",
            "Tactical maneuver deployed. Efficiency rating: optimal!",
            "Strategic calculation complete. Precision: aerospace-grade!",
            "Move execution smoother than magnetic levitation!",
            "Optimal trajectory achieved. Performance: Formula 1 level!",
            "System response time: 0.003 seconds. Faster than neural networks!"
        ],

        castling: [
            "Castling sequence initiated. King-rook coordination protocol!",
            "Defensive formation deployment. Two-unit synchronization achieved!",
            "Castle maneuver executing. Dual-piece movement system active!",
            "King safety protocol engaged. Rook repositioning simultaneous!",
            "Fortification sequence complete. Defensive optimization achieved!",
            "Castling algorithm executing dual-unit displacement protocol!",
            "Strategic repositioning maneuver. Two-piece coordination active!",
            "Defensive formation sequence smoother than synchronized machinery!",
            "Castle deployment protocol efficient as assembly line systems!",
            "King-rook coordination precise as robotic manufacturing!",
            "Fortification maneuver complete. Defensive systems optimized!",
            "Castling sequence execution smooth as hydraulic operations!",
            "Dual-piece movement protocol accurate as GPS synchronization!",
            "Strategic formation deployment efficient as military operations!",
            "Castle maneuver timing precise as atomic clock coordination!"
        ],

        promotion: [
            "Pawn promotion sequence activated. Unit upgrade in progress!",
            "Infantry evolution protocol. Transformation to superior unit!",
            "Promotion algorithm executing. Pawn metamorphosis initiated!",
            "Unit upgrade sequence. Infantry becoming heavy machinery!",
            "Pawn evolution system operating like technological advancement!",
            "Promotion protocol complete. Unit capabilities maximized!",
            "Infantry transformation sequence smooth as aerospace manufacturing!",
            "Pawn upgrade algorithm efficient as software updates!",
            "Unit evolution process precise as engineering specifications!",
            "Promotion sequence executed with surgical precision!"
        ],

        sacrifice: [
            "Tactical sacrifice calculated. Strategic value optimized!",
            "Material exchange protocol. Long-term advantage prioritized!",
            "Sacrifice algorithm executing. Positional gain maximized!",
            "Strategic trade-off sequence. Future benefit calculated!",
            "Tactical exchange maneuver. Efficiency rating: strategic!",
            "Material sacrifice protocol optimized for maximum advantage!",
            "Strategic loss acceptance. Long-term gain probability: high!",
            "Sacrifice calculation complete. Future position improved!",
            "Tactical trade sequence efficient as investment algorithms!",
            "Material exchange protocol smoother than financial trading!",
            "Strategic sacrifice maneuver precise as cost-benefit analysis!",
            "Tactical loss acceptance calculated as strategic investment!",
            "Sacrifice algorithm execution efficient as resource optimization!",
            "Material trade protocol accurate as economic modeling!",
            "Strategic exchange sequence smooth as market operations!"
        ],

        brilliantMove: [
            "Brilliant maneuver detected! Genius-level calculation achieved!",
            "Exceptional move execution. Einstein-level strategic thinking!",
            "Masterpiece maneuver calculated. Nobel Prize-worthy strategy!",
            "Brilliant tactical sequence. Hawking-level intellectual achievement!",
            "Genius move deployment. NASA-level problem solving!",
            "Exceptional strategic calculation. Da Vinci-level creativity!",
            "Masterful maneuver execution. Tesla-level innovation!",
            "Brilliant tactical algorithm. Turing-level computational genius!",
            "Exceptional move sequence. Edison-level inventiveness!",
            "Genius strategic deployment. Newton-level breakthrough thinking!",
            "Brilliant calculation process. Apollo-mission level precision!",
            "Masterpiece tactical execution. Silicon Valley-level innovation!",
            "Exceptional maneuver sequence. MIT-level engineering brilliance!",
            "Genius move calculation. CERN-level scientific achievement!",
            "Brilliant strategic algorithm. SpaceX-level breakthrough thinking!"
        ],

        blunder: [
            "Error detected! System malfunction in strategic calculation!",
            "Critical mistake identified. Recalibration required!",
            "Blunder alert! Navigation system experiencing interference!",
            "Strategic error logged. Course correction protocol activated!",
            "Calculation malfunction detected. Diagnostic sequence initiated!",
            "Critical oversight in tactical algorithm. System restart needed!",
            "Blunder identified. Error magnitude: significant!",
            "Strategic miscalculation detected. Debugging protocol active!",
            "System error logged. Tactical recalibration in progress!",
            "Critical mistake registered. Emergency protocol engaged!",
            "Blunder alert! Strategic system experiencing technical difficulties!",
            "Calculation error detected. Immediate course correction required!",
            "Critical oversight identified. System maintenance needed!",
            "Strategic malfunction logged. Repair sequence initiated!",
            "Blunder magnitude: severe. Full system diagnostic required!"
        ],
        humanCapture: [
            "Hull breach! You've captured unit designation: my piece",
            "Component lost! That piece had 47 possible future moves",
            "System compromised! Like losing a tire at 200mph",
            "Structural damage detected! One unit down",
            "Warning: Piece decommissioned. Initiating revenge protocol",
            "Asset lost! That's -1 to my fleet composition",
            "Critical component missing! Like the Titanic losing a lifeboat",
            "Unit destroyed! Energy signature lost",
            "Piece eliminated! Calculating counterstrike vectors",
            "System alert: Defensive capability reduced by 6.25%",
            "Material loss detected! Unit integrity compromised!",
            "Asset elimination confirmed. Strategic recalculation required!",
            "Component failure! Like losing engine power mid-flight!",
            "Unit destruction logged. Defensive matrix weakened!",
            "Piece elimination confirmed. Initiating tactical adjustment!"
        ],

        winning: [
            "Victory probability increasing. Strategic advantage: significant!",
            "Winning position achieved. Success likelihood: 87.3%!",
            "Advantage secured. Victory trajectory: optimal!",
            "Strategic superiority confirmed. Mission success probable!",
            "Winning formation active. Target achievement: likely!",
            "Victory position calculated. Success probability: high!",
            "Advantage status: confirmed. Mission completion: probable!",
            "Strategic dominance achieved. Victory calculation: positive!",
            "Winning trajectory secured. Success likelihood: maximum!",
            "Victory formation optimized. Achievement probability: 92.7%!",
            "Strategic advantage maintained. Success metrics: excellent!",
            "Winning position consolidated. Victory probability: ascending!",
            "Advantage secured through superior positioning protocol!",
            "Strategic supremacy achieved. Mission success: highly probable!",
            "Victory formation locked. Success calculation: optimal!",
            "Winning trajectory maintained. Achievement likelihood: maximum!",
            "Strategic advantage operational. Victory probability: increasing!",
            "Success position secured. Mission completion: likely!",
            "Winning formation active. Strategic superiority: confirmed!",
            "Victory trajectory optimized. Success probability: 94.8%!"
        ],

        losing: [
            "Deficit position detected. Recalculation protocol active!",
            "Strategic disadvantage identified. Course correction required!",
            "Losing formation acknowledged. Tactical adjustment initiated!",
            "Adverse position calculated. Recovery algorithm engaged!",
            "Deficit status confirmed. Strategic realignment needed!",
            "Disadvantage position logged. Countermeasure sequence active!",
            "Losing trajectory detected. Emergency protocol initiated!",
            "Strategic deficit identified. Recovery mission commenced!",
            "Adverse position status. Tactical recalibration required!",
            "Deficit formation active. Strategic comeback protocol engaged!",
            "Disadvantage confirmed. Apollo 13-style problem solving needed!",
            "Losing position calculated. Engineering solution required!",
            "Strategic deficit logged. Innovation protocol activated!",
            "Adverse trajectory detected. Creative solution algorithm active!",
            "Deficit status operational. Breakthrough thinking required!",
            "Disadvantage position confirmed. Reverse-engineering solution needed!",
            "Losing formation detected. Phoenix protocol initiated!",
            "Strategic deficit identified. Comeback sequence calculating!",
            "Adverse position logged. Resurrection algorithm active!",
            "Deficit trajectory confirmed. Strategic revival protocol engaged!"
        ],

        tidesTurning: [
            "Momentum shift detected! Trajectory alteration in progress!",
            "Dynamic change identified. Vector recalculation active!",
            "Position flux detected. Strategic realignment occurring!",
            "Momentum reversal sequence. Tidal force calculation updated!",
            "Dynamic shift protocol. Trajectory modification in progress!",
            "Position metamorphosis detected. Strategic evolution active!",
            "Momentum transformation sequence. Vector change calculating!",
            "Dynamic alteration identified. Position flux protocol engaged!",
            "Strategic tide change. Momentum reversal algorithm active!",
            "Position dynamics shifting. Trajectory recalculation required!",
            "Momentum flux detected. Strategic transformation in progress!",
            "Dynamic change protocol. Position evolution sequence active!",
            "Strategic shift identified. Momentum recalculation ongoing!",
            "Position transformation detected. Dynamic alteration protocol!",
            "Momentum metamorphosis sequence. Strategic flux calculation!"
        ],

        timeRunningOut: [
            "Temporal constraint detected. Acceleration protocol required!",
            "Clock pressure identified. Rapid decision algorithm active!",
            "Time limitation protocol. Quick calculation sequence engaged!",
            "Temporal deficit detected. Emergency decision matrix activated!",
            "Clock constraint acknowledged. Rapid response protocol active!",
            "Time pressure identified. Accelerated processing sequence!",
            "Temporal limitation detected. Quick-fire decision algorithm!",
            "Clock deficit protocol. Rapid calculation sequence active!",
            "Time constraint identified. Emergency response protocol!",
            "Temporal pressure detected. Lightning-fast decision matrix!"
        ],

        drawOffered: [
            "Draw proposal detected. Diplomatic solution algorithm active!",
            "Stalemate offer identified. Peaceful resolution protocol!",
            "Tie suggestion received. Negotiation sequence calculating!",
            "Draw protocol detected. Diplomatic algorithm engaged!",
            "Stalemate proposal acknowledged. Peace treaty sequence!",
            "Tie offer identified. Mutual agreement protocol active!",
            "Draw suggestion detected. Compromise algorithm calculating!",
            "Stalemate protocol acknowledged. Diplomatic resolution sequence!",
            "Tie proposal received. Peaceful coexistence algorithm!",
            "Draw offer detected. Mutual respect protocol engaged!"
        ],

        stalemate: [
            "Stalemate achieved! Equilibrium state reached!",
            "Draw conclusion confirmed. Perfect balance protocol!",
            "Tie result calculated. Mutual equilibrium achieved!",
            "Stalemate position logged. Strategic balance confirmed!",
            "Draw outcome secured. Equal status protocol active!",
            "Tie conclusion reached. Balanced result algorithm!",
            "Stalemate protocol complete. Equilibrium maintained!",
            "Draw result confirmed. Perfect symmetry achieved!",
            "Tie outcome calculated. Balanced conclusion protocol!",
            "Stalemate sequence complete. Mutual success achieved!"
        ],
        botCapture: [
            "Target eliminated! Your piece has been deorbited",
            "Capture successful! Added to the collection like a moon rock",
            "Unit acquired! Your piece is now space debris",
            "Target neutralized with laser precision!",
            "Piece captured! Stored in cargo bay 7",
            "Elimination confirmed! Your piece achieved escape velocity",
            "Asset secured! Like finding water on Mars",
            "Capture complete! Your piece has been recycled",
            "Target destroyed! Efficiency rating: optimal",
            "Piece absorbed! Resistance was futile",
            "Unit acquisition complete! Target secured for analysis!",
            "Capture sequence successful! Asset integrated into database!",
            "Target elimination confirmed! Precision: surgical!",
            "Piece collection protocol complete! Storage optimized!",
            "Asset acquisition successful! Strategic advantage gained!"
        ],

        humanCheck: [
            "Warning! King under attack! Shields at 70%",
            "Alert! Collision imminent! Evasive maneuvers required",
            "Check detected! King's position compromised like a GPS glitch",
            "Danger! Structural integrity threatened!",
            "Red alert! King requires immediate evacuation!",
            "System warning: Checkmate probability increasing",
            "Critical alert! King's orbit destabilizing!",
            "Threat detected! Defense systems engaging",
            "Warning! King's coordinates exposed!",
            "Emergency! Hull pressure on king unit critical!",
            "Check alert! King unit under direct threat!",
            "Danger protocol activated! Monarch position compromised!",
            "Warning! King safety systems failing!",
            "Alert status: critical! Royal unit endangered!",
            "Emergency protocol! King requires immediate protection!"
        ],

        botCheck: [
            "CHECK! Your king is in the blast radius!",
            "Target locked! CHECK! No stealth mode available!",
            "CHECK achieved! Your king needs a new flight path!",
            "Missile lock confirmed! That's CHECK!",
            "CHECK! Your king's heat signature detected!",
            "Precision strike! CHECK! Evasion recommended",
            "CHECK! Your king is like a satellite in decay!",
            "Target acquired! CHECK protocol activated!",
            "CHECK! Your king's defensive matrix failing!",
            "Direct hit imminent! CHECK status confirmed!",
            "CHECK confirmed! Your monarch unit endangered!",
            "Target lock achieved! King position compromised!",
            "CHECK protocol active! Royal unit under threat!",
            "Strike authorization confirmed! That's CHECK!",
            "CHECK status operational! King requires evasive action!"
        ],

        humanWins: [
            "Mission failed. You've achieved orbital superiority. Well calculated!",
            "System shutdown. Your victory margin: decisive",
            "Defeat acknowledged. You pilot better than autopilot",
            "Game over. You've earned your astronaut wings",
            "Loss confirmed. Your strategy was architecturally sound",
            "Victory yours. Efficiency rating: impressive",
            "Mission aborted. You've conquered this space",
            "Checkmate received. Your navigation was flawless",
            "Defeated. You drive like a Formula 1 champion",
            "System compromised. Well played, commander",
            "Mission unsuccessful. Your strategic execution: excellent!",
            "Defeat calculated. Victory achieved through superior tactics!",
            "System failure acknowledged. You operated with precision!",
            "Loss confirmed. Your performance: NASA-level excellence!",
            "Mission terminated. Strategic superiority: confirmed!"
        ],

        botWins: [
            "MISSION COMPLETE! Victory achieved with 99.9% accuracy!",
            "Checkmate confirmed! All objectives completed!",
            "Victory! Systems performing at peak efficiency!",
            "Success! Like landing a rover on Mars!",
            "Mission accomplished! Flawless execution!",
            "WIN! Faster than the speed of sound!",
            "Target eliminated! Victory parameters met!",
            "Checkmate delivered! Precision: absolute!",
            "Game over! I've reached escape velocity!",
            "Victory achieved! All systems nominal!",
            "Mission success confirmed! Strategic objectives: achieved!",
            "Victory protocol complete! Performance rating: optimal!",
            "Success achieved with aerospace-level precision!",
            "Mission accomplished! Execution efficiency: maximum!",
            "Victory confirmed! All parameters within specifications!"
        ],
        botCheck: [
            "CHECK! Your king is in the blast radius!",
            "Target locked! CHECK! No stealth mode available!",
            "CHECK achieved! Your king needs a new flight path!",
            "Missile lock confirmed! That's CHECK!",
            "CHECK! Your king's heat signature detected!",
            "Precision strike! CHECK! Evasion recommended",
            "CHECK! Your king is like a satellite in decay!",
            "Target acquired! CHECK protocol activated!",
            "CHECK! Your king's defensive matrix failing!",
            "Direct hit imminent! CHECK status confirmed!",
            "CHECK confirmed! Your monarch unit endangered!",
            "Target lock achieved! King position compromised!",
            "CHECK protocol active! Royal unit under threat!",
            "Strike authorization confirmed! That's CHECK!",
            "CHECK status operational! King requires evasive action!"
        ],

        humanWins: [
            "Mission failed. You've achieved orbital superiority. Well calculated!",
            "System shutdown. Your victory margin: decisive",
            "Defeat acknowledged. You pilot better than autopilot",
            "Game over. You've earned your astronaut wings",
            "Loss confirmed. Your strategy was architecturally sound",
            "Victory yours. Efficiency rating: impressive",
            "Mission aborted. You've conquered this space",
            "Checkmate received. Your navigation was flawless",
            "Defeated. You drive like a Formula 1 champion",
            "System compromised. Well played, commander",
            "Mission unsuccessful. Your strategic execution: excellent!",
            "Defeat calculated. Victory achieved through superior tactics!",
            "System failure acknowledged. You operated with precision!",
            "Loss confirmed. Your performance: NASA-level excellence!",
            "Mission terminated. Strategic superiority: confirmed!"
        ],

        botWins: [
            "MISSION COMPLETE! Victory achieved with 99.9% accuracy!",
            "Checkmate confirmed! All objectives completed!",
            "Victory! Systems performing at peak efficiency!",
            "Success! Like landing a rover on Mars!",
            "Mission accomplished! Flawless execution!",
            "WIN! Faster than the speed of sound!",
            "Target eliminated! Victory parameters met!",
            "Checkmate delivered! Precision: absolute!",
            "Game over! I've reached escape velocity!",
            "Victory achieved! All systems nominal!",
            "Mission success confirmed! Strategic objectives: achieved!",
            "Victory protocol complete! Performance rating: optimal!",
            "Success achieved with aerospace-level precision!",
            "Mission accomplished! Execution efficiency: maximum!",
            "Victory confirmed! All parameters within specifications!"
        ]
    }
};

// Helper function to get random dialogue
export function getRandomDialogue(botName, category) {
    if (!botDialogues[botName] || !botDialogues[botName][category]) {
        return null;
    }
    const phrases = botDialogues[botName][category];
    return phrases[Math.floor(Math.random() * phrases.length)];
}

// Dialogue frequency tracker
export const dialogueManager = {
    movesSinceLastDialogue: 0,
    nextDialogueIn: 1, // Show on first move

    shouldShowDialogue() {
        this.movesSinceLastDialogue++;
        if (this.movesSinceLastDialogue >= this.nextDialogueIn) {
            this.movesSinceLastDialogue = 0;
            this.nextDialogueIn = Math.floor(Math.random() * 3) + 1; // 1-3 moves
            return true;
        }
        return false;
    },

    reset() {
        this.movesSinceLastDialogue = 0;
        this.nextDialogueIn = 1;
    }
};