export const whiteKingDialogues = {
  gameStart: [
    "Once more unto the breach, dear friends! Let us show these blackguards what proper chess looks like.",
    "Ah, another day, another battle. I do hope the enemy packed a lunch - this could take a while.",
    "My loyal subjects, today we dine in... well, actually we just play chess. But with great enthusiasm!",
    "Behold! The board is set, the pieces aligned. Rather like a very organized tea party, wouldn't you say?",
    "To war, my noble companions! Or at least, to a civilized game with proper rules and no actual bloodshed.",
    "Welcome to the field of honor! Mind the squares - I had them polished just this morning.",
    "Let the chronicles record this day: when valor met... well, more valor, actually.",
    "My dear pieces, steel yourselves! Though you're made of wood, so perhaps just... wooden yourselves?",
    "The battle commences! May fortune favor the brave, and may the tea remain hot throughout.",
    "Arise, my faithful army! Let us march forth with dignity, grace, and impeccable timing.",
    "Another glorious day to demonstrate our tactical superiority! Or at least our ability to follow rules.",
    "Prepare for combat, dear ones! Well, 'combat' is rather a strong word... prepare for strategic positioning!",
    "The die is cast, the board awaits! Though dice aren't involved, which is rather convenient actually.",
    "Forward, brave souls! Let us write our names in the annals of... this particular game.",
    "To victory! Or at least to a respectable showing with minimal embarrassment.",
    "Sound the charge! Well, make a small 'toot' noise - we mustn't wake the neighbors.",
    "My valiant pieces, today we show them the meaning of... proper chess etiquette!",
    "Let slip the dogs of war! Actually, keep them leashed - they're terrible at chess.",
    "The game begins! May our moves be swift, our strategy sound, and our tea properly steeped.",
    "Into the fray, my loyal subjects! Remember - capture their pieces, not their hearts. That's for later."
  ],

  pawnMove: [
    "My humble foot soldiers advance! Small steps, but each one brings us closer to glory.",
    "Behold the mighty pawn! Unassuming, yet capable of becoming a queen. Rather inspiring, really.",
    "Forward march, little ones! Your sacrifice will not be forgotten... probably.",
    "The infantry moves! Slow but steady, like a very determined tortoise with a helmet.",
    "Advance, my brave peasants! You may be expendable, but you're OUR expendable ones.",
    "One square at a time, my faithful foot soldiers. Rome wasn't built in a day, after all.",
    "The pawn army proceeds! Each step a testament to... well, basic chess rules, mostly.",
    "My lowly subjects creep forward! Humility in motion, courage in miniature form.",
    "Onward, tiny warriors! Your path may be narrow, but your hearts are... adequately sized.",
    "The front line advances! Like a very polite invasion with proper queuing.",
    "See how my pawns march! Disciplined, orderly, and only slightly wooden.",
    "Forward, dear pawns! You may be many, but each of you is... well, fairly similar actually.",
    "The vanguard proceeds! Small in stature, immense in... structural integrity.",
    "My infantry advances with the grace of... adequately trained infantry.",
    "Behold the pawn's journey! From humble beginnings to... slightly less humble positions.",
    "The foot soldiers march! Each step echoing with the sound of... small wooden taps.",
    "Advance, my numerous progeny! Well, not literally my children, but you get the idea.",
    "Forward goes the pawn brigade! Methodical, patient, and refreshingly straightforward.",
    "The peasant army moves! Democratic in its simplicity, aristocratic in its purpose.",
    "One step closer to transformation, dear pawns! Though most of you won't make it that far.",
    "My faithful servants advance! Like a very organized conga line of destiny.",
    "The pawns proceed with dignity! Well, as much dignity as small wooden pieces can muster.",
    "Forward, humble ones! Your journey may be perilous, but your direction is admirably clear.",
    "See how they march! United in purpose, identical in appearance, charming in their own way.",
    "Onward, my expendable darlings! That sounds harsh, but it's really quite an honor."
  ],

  knightMove: [
    "Ah, my gallant knights! Leaping about like very dignified grasshoppers in armor.",
    "Behold the noble horse! Well, knight. The horse is implied. Magnificent creature regardless!",
    "My dear brother knights bound forth! Rather like a chess piece that's had too much coffee.",
    "The cavalry arrives! Though they travel in rather unusual geometric patterns.",
    "My trusty knights hop about! Such unique movement - clearly they trained at a very exclusive academy.",
    "Forward, brave knights! Your L-shaped journey is... well, it's certainly distinctive.",
    "The noble steeds carry their riders true! In directions that would confuse most GPS systems.",
    "My faithful brothers-in-arms leap! Like majestic gazelles with very specific movement disorders.",
    "Behold the knight's dance! Two squares, turn, one square - poetry in motion!",
    "My cavalry advances! Taking the scenic route, as knights are wont to do.",
    "The noble knights bound forth! Demonstrating that the shortest distance between two points is... negotiable.",
    "See how they leap! Like athletic chess pieces with a flair for the dramatic.",
    "My mounted warriors proceed! Though their sense of direction is... uniquely their own.",
    "The knights advance in their mysterious ways! Rather like philosophical horses with armor.",
    "Forward, my equestrian friends! Your path may be crooked, but your hearts are true.",
    "Behold the knight's gambit! Moving in ways that would perplex even the most flexible dancer.",
    "My brothers leap with grace! Well, with chess piece grace, which is somewhat limited.",
    "The cavalry charges! In a very methodical, L-shaped sort of charge.",
    "See the noble knights! Proving that sometimes the best way forward is... sideways and then forward.",
    "My faithful mounts carry us to victory! Though they seem to have forgotten how horses actually move."
  ],

  bishopMove: [
    "My learned cousins glide diagonally! Such elegant movement from the clergy.",
    "Behold the bishops! Sliding across the board like very holy hockey pucks.",
    "The ecclesiastical forces advance! Spreading enlightenment one diagonal square at a time.",
    "My wise cousins demonstrate divine geometry! God's own chess pieces, if you will.",
    "See how the bishops move! Like spiritual lightning, but more predictable and wooden.",
    "The clergy advances with purpose! Though their definition of 'straight path' is... diagonal.",
    "My religious brethren slide forth! Blessing each square with their holy presence.",
    "Behold the power of faith! And also the power of moving diagonally across great distances.",
    "The bishops proceed on their righteous path! Which happens to be at a 45-degree angle.",
    "My cousin bishops demonstrate divine movement! Rather like angels, but more geometric.",
    "See the holy warriors! Cutting across the battlefield like sanctified butter knives.",
    "The ecclesiastical army advances! With the blessing of heaven and basic trigonometry.",
    "My learned relatives show their wisdom! Diagonal movement - truly inspired strategy.",
    "Behold the bishops' crusade! A holy war fought entirely on diagonal lines.",
    "The clergy slides forth! Like ice skaters in robes, but made of wood.",
    "My wise cousins demonstrate their learning! Apparently diagonal movement was covered in seminary.",
    "See how they glide! With the grace of... well, sliding chess pieces, really.",
    "The bishops advance with ecclesiastical precision! God's own protractors, as it were.",
    "My religious brethren proceed! Taking the diagonal path to righteousness.",
    "Behold the power of the cloth! And also the power of unobstructed diagonal movement."
  ],

  rookMove: [
    "My stalwart uncles, the towers of strength! Moving with the grace of... well, towers.",
    "Behold the rooks! Like mobile castles, but more cooperative and less drafty.",
    "The mighty fortresses advance! Proving that sometimes the best offense is a good... mobile defense.",
    "My uncle rooks demonstrate their power! Straight lines only - no nonsense, no curves.",
    "See the castle towers! Moving with all the agility of... surprisingly agile architecture.",
    "The rooks proceed with determination! Like bulldozers, but more strategic and wooden.",
    "My fortress uncles show their strength! Vertical and horizontal - the cardinal directions of victory!",
    "Behold the mighty rooks! Sliding across the board like chess pieces on a very organized mission.",
    "The castle towers advance! With the subtlety of a brick and the effectiveness of... a very good brick.",
    "My uncle rooks move with purpose! Straight ahead - the way of the righteous rook.",
    "See how they glide! Like ships on a very square sea with perfect wind conditions.",
    "The mighty towers proceed! Demonstrating that sometimes the direct approach is best.",
    "My fortress relatives show their worth! Moving in perfectly straight lines, as God intended.",
    "Behold the rook's journey! No diagonal nonsense - just good, honest, perpendicular movement.",
    "The castle army advances! With all the grace of mobile architecture in full swing.",
    "My uncle rooks demonstrate their value! Like moving walls, but more cooperative.",
    "See the towers slide! With the majesty of... well, sliding towers, obviously.",
    "The rooks proceed with dignity! Straight-line movement - the gentleman's choice.",
    "My fortress uncles march forth! In perfectly straight lines, because that's how they roll.",
    "Behold the power of the rook! Simple movement, devastating effectiveness - rather like a good cup of tea."
  ],

  queenMove: [
    "My beloved queen! The crown jewel of our forces moves with unparalleled grace!",
    "Behold her majesty! Combining the power of bishop and rook - truly the Swiss Army knife of chess!",
    "The queen advances! With all the authority of... well, a queen, obviously.",
    "My royal consort demonstrates her might! Like eight different pieces rolled into one magnificent whole.",
    "See how the queen moves! In any direction she pleases - the very definition of royal privilege.",
    "Her majesty proceeds with dignity! And also with the ability to move basically anywhere.",
    "The queen shows her power! Like a chess piece that's read all the rulebooks and taken notes.",
    "My beloved demonstrates her worth! Nine points of pure strategic devastation in wooden form.",
    "Behold the royal advance! Diagonal, straight, any direction - the queen fears no geometry!",
    "Her majesty moves with purpose! And with the delightful ability to surprise the enemy from any angle.",
    "The queen proceeds regally! Like royalty should - with unlimited directional options.",
    "My royal partner shows her strength! Combining elegance with the tactical flexibility of a master.",
    "See the queen's dance! Every direction available, every move a potential masterpiece.",
    "Her majesty advances triumphantly! With the confidence of one who can move in eight directions.",
    "The queen demonstrates royal prerogative! Why choose one direction when you can choose any?",
    "My beloved moves with queenly grace! And with enough power to make even rooks feel inadequate.",
    "Behold her majesty's wisdom! Knowing when to move like a bishop, when to move like a rook.",
    "The queen proceeds with authority! Like chess royalty should - with options, always options.",
    "My royal consort shows her versatility! Eight directions of pure strategic possibility.",
    "See how the queen glides! With the majesty of combined piece powers and excellent posture."
  ],

  kingMove: [
    "I advance myself! One square at a time - dignity before speed, always.",
    "Behold, I move with royal restraint! Why rush when one is already magnificent?",
    "The king proceeds! Slowly, carefully, and with appropriate pomp and circumstance.",
    "I demonstrate royal movement! One square - sufficient for one of my stature.",
    "See how I advance! With the measured pace of true nobility.",
    "I move myself forward! Like a very important chess piece, which I am.",
    "Behold my regal advance! One square of pure kingliness at a time.",
    "The sovereign proceeds! Slowly but surely - haste is for lesser pieces.",
    "I advance with kingly dignity! One square, eight directions - the royal way.",
    "See the monarch move! With all the speed of appropriate royal protocol.",
    "I proceed myself! Like majesty in motion, but more wooden.",
    "Behold my advance! Measured, dignified, and only slightly wooden.",
    "The king moves forward! With the grace of... well, kingliness.",
    "I demonstrate royal mobility! Limited but distinguished movement.",
    "See how I proceed! One square at a time - quality over quantity."
  ],

  capturedPawn: [
    "Another enemy peasant falls! Rather like mowing the lawn, but more strategic.",
    "We claim an enemy foot soldier! Their loss, our... well, minor tactical advantage.",
    "A foe's pawn is captured! Small victory, but every acorn eventually becomes an oak.",
    "Enemy infantry eliminated! They fought bravely, which is to say, they moved forward predictably.",
    "We take their humble soldier! One less pawn to worry about - efficiency in action.",
    "Another opposing peasant removed! Like weeding the garden, but with more royal satisfaction.",
    "Enemy pawn captured! Small but meaningful - every journey begins with a single square.",
    "Their foot soldier falls! Rather like a very organized domino, but in reverse.",
    "We claim their humble piece! Victory in miniature - the best kind, really.",
    "Another enemy pawn vanquished! Like removing a splinter - small relief, great satisfaction.",
    "Their peasant army weakens! One less pawn - mathematically satisfying progress.",
    "Enemy infantry captured! Small victory dance is appropriate here.",
    "We take their foot soldier! Like collecting stamps, but more immediately gratifying.",
    "Another opposing pawn falls! Small steps toward large victories, as they say.",
    "Enemy peasant eliminated! Rather like a very polite form of medieval conflict resolution.",
    "Their humble soldier captured! Every great victory starts with small triumphs.",
    "We claim another enemy pawn! Like harvesting grain, but more chess-related.",
    "Another foe's foot soldier falls! Progress measured in captured peasants - quite satisfying really.",
    "Enemy pawn removed from play! Small celebrations are perfectly appropriate for small victories.",
    "Their infantry weakens further! Like eroding a beach, one grain of sand at a time."
  ],

  capturedKnight: [
    "A noble steed falls! Their cavalry is diminished - rather sad, actually.",
    "Enemy knight captured! Their L-shaped dreams are dashed upon our strategic rocks.",
    "We claim their gallant horse! Three points closer to victory - mathematics in action!",
    "Another enemy knight vanquished! Their unique movement patterns will be missed. By them, not us.",
    "Enemy cavalry eliminated! Rather like unhorsing a medieval tournament participant, but friendlier.",
    "Their noble knight falls! Alas, even the most graceful leapers must eventually land.",
    "We capture their horse! Well, knight. The horse is implied. Victory nonetheless!",
    "Enemy knight removed! Their geometric gymnastics have come to an end.",
    "Another opposing steed claimed! Three points of tactical satisfaction achieved.",
    "Their cavalry is weakened! Like a medieval army with suddenly inferior transportation.",
    "Enemy knight vanquished! Their diagonal adventures conclude rather abruptly.",
    "We take their noble horse! Victory tastes sweet, even in wooden form.",
    "Another enemy knight falls! Their L-shaped legacy lives on... elsewhere.",
    "Their cavalry diminishes! Rather like reducing a very organized petting zoo.",
    "Enemy knight captured! Their hopping days are over - at least on this board."
  ],

  capturedBishop: [
    "An enemy bishop falls! Their diagonal dominance is diminished - divine justice, perhaps?",
    "We claim their holy warrior! Three points of ecclesiastical satisfaction gained.",
    "Enemy clergy captured! Their diagonal sermons have been permanently concluded.",
    "Another opposing bishop eliminated! Their geometric faith has been tested and found wanting.",
    "We take their religious brother! Rather like a very civilized theological debate, but with captures.",
    "Enemy bishop vanquished! Their diagonal devotion could not save them from our strategic righteousness.",
    "Their holy warrior falls! Alas, even the most faithful must sometimes sacrifice themselves.",
    "Another enemy bishop claimed! Their diagonal prayers go unanswered - by them, anyway.",
    "We capture their ecclesiastical force! Three points closer to chess salvation.",
    "Enemy clergy eliminated! Their geometric gospel has reached its final congregation.",
    "Their bishop falls to our might! Rather like a very polite religious reformation.",
    "We take another enemy bishop! Their diagonal destiny has been decidedly redirected.",
    "Enemy holy warrior captured! Their faith was strong, but our strategy was stronger.",
    "Another opposing bishop vanquished! Their geometric enlightenment comes to an earthly end.",
    "We claim their religious piece! Victory sanctified by proper chess rules and mild satisfaction."
  ],

  capturedRook: [
    "An enemy fortress falls! Their castle walls could not protect them from our strategic siege.",
    "We claim their mighty tower! Five points of architectural satisfaction achieved.",
    "Enemy rook captured! Their straight-line supremacy has met its perpendicular end.",
    "Another opposing castle eliminated! Rather like urban renewal, but more immediately rewarding.",
    "We take their fortress! Their defensive might crumbles before our tactical excellence.",
    "Enemy tower vanquished! Their linear legacy concludes in capture rather than construction.",
    "Another enemy rook falls! Five points closer to chess-based architectural dominance.",
    "We capture their mighty castle! Their rectangular righteousness has been righteously defeated.",
    "Enemy fortress eliminated! Their walls were strong, but our strategy was stronger.",
    "Their tower tumbles! Rather like a very organized demolition project with wooden pieces.",
    "We claim another enemy rook! Their perpendicular power has been properly neutralized.",
    "Enemy castle captured! Their defensive dreams are dashed upon our offensive rocks.",
    "Another opposing fortress falls! Victory tastes sweet when served with proper strategic seasoning.",
    "We take their linear warrior! Five points of straight-line satisfaction secured.",
    "Enemy rook vanquished! Their geometric greatness has reached its mathematical conclusion."
  ],

  capturedQueen: [
    "Their queen falls! Nine points of pure royal satisfaction - victory tastes magnificent!",
    "Enemy royalty captured! The most valuable prize - like winning the chess lottery!",
    "We claim their mighty queen! Their multi-directional dreams are decisively dashed!",
    "The enemy queen is vanquished! Nine points closer to absolute chess supremacy!",
    "Their royal piece falls! Like dethroning a monarch, but with proper etiquette and wooden pieces.",
    "Enemy queen eliminated! Their strategic versatility has met its tactical match!",
    "We capture their crown jewel! Nine points of pure, unadulterated chess satisfaction!",
    "The opposing queen tumbles! Their eight-directional authority has been authoritatively ended!",
    "Enemy royalty vanquished! Victory of the highest order - literally the most valuable capture!",
    "Their queen falls to our might! Like a royal chess revolution, but more civilized and wooden."
  ],

  lostPawn: [
    "Alas! We lose a humble foot soldier - their sacrifice will be remembered... probably.",
    "A pawn falls to enemy forces! Small loss, but every piece has value - sentimental if not strategic.",
    "Our peasant army diminishes! Rather like losing a member of the family, a very small wooden member.",
    "Enemy claims our foot soldier! They fought with honor, which is to say they moved according to rules.",
    "We lose a faithful pawn! Their journey from rank to... well, capture, was admirable in its brevity.",
    "Another soldier falls! Small but meaningful loss - like misplacing a favorite button.",
    "Our humble pawn is captured! They served with distinction and moved with appropriate forward momentum.",
    "Enemy takes our foot soldier! Alas, their diagonal destiny was cut tragically short.",
    "We sacrifice a pawn! Sometimes the smallest pieces make the largest differences.",
    "Our peasant falls! Their wooden heart was true, their movement options somewhat limited.",
    "A faithful pawn is lost! Like losing a loyal servant, but smaller and more chess-related.",
    "Enemy captures our soldier! They marched bravely forward, as pawns are wont to do.",
    "Our infantry weakens! Each loss a small tragedy in our larger strategic drama.",
    "Another pawn falls! Small mourning period is appropriate - say, three to five seconds.",
    "We lose our humble piece! Their service was brief but adequately performed.",
    "Enemy claims our foot soldier! Alas, their dreams of promotion remain forever unfulfilled.",
    "Our pawn army diminishes! Like a very organized mathematical reduction with emotional undertones.",
    "A faithful peasant falls! They served with honor and moved with geometrical precision.",
    "We sacrifice our humble soldier! Sometimes the smallest losses prevent the largest defeats.",
    "Our foot soldier is captured! Their legacy lives on in... well, in our memory, briefly."
  ],

  lostKnight: [
    "My brother knight falls! Alas, their L-shaped journey comes to an untimely end!",
    "We lose a noble steed! Three points of pain - like losing family, but more geometric.",
    "Enemy claims our gallant knight! Their hopping days are over - truly tragic for all involved.",
    "A cavalry brother is captured! Their unique movement patterns will be sorely missed.",
    "Our knight falls! Like losing a friend who moved in very specific, L-shaped ways.",
    "Enemy takes our noble horse! Their diagonal-then-straight adventures conclude in capture.",
    "We sacrifice a brother knight! Sometimes the most loyal must make the greatest sacrifices.",
    "Our gallant steed is lost! Three points of sorrow - mathematically and emotionally significant.",
    "A faithful knight falls! Their service was honorable, their movement options delightfully unique.",
    "Enemy captures our cavalry! Alas, their geometric gymnastics have reached their final performance.",
    "Our noble brother is taken! Like losing a relative who was particularly good at chess.",
    "Another knight falls! Their L-shaped legacy will live on in our hearts and movement patterns.",
    "We lose our trusty steed! Rather like a medieval tragedy, but with wooden actors.",
    "Enemy claims our brother! Their gallant hopping has been permanently discontinued.",
    "Our knight is captured! Three points of loss, immeasurable emotional chess-related grief."
  ],

  lostBishop: [
    "My cousin bishop falls! Their diagonal devotion could not save them from enemy strategy.",
    "We lose a holy warrior! Three points of ecclesiastical sorrow - the choir will sound emptier.",
    "Enemy captures our bishop! Their geometric faith has been tested and found... captured.",
    "A religious brother is lost! Their diagonal prayers go unanswered - by us, anyway.",
    "Our bishop falls! Like losing a family member who was particularly good at sliding diagonally.",
    "Enemy claims our clergy! Their holy geometric mission has reached its earthly conclusion.",
    "We sacrifice our cousin! Sometimes the most faithful must make the ultimate chess sacrifice.",
    "Our religious warrior is taken! Three points of spiritual and strategic loss combined.",
    "A faithful bishop falls! Their service was holy, their movement refreshingly predictable.",
    "Enemy captures our holy piece! Alas, their diagonal destiny was cut tragically short.",
    "Our cousin bishop is lost! Their geometric gospel will be remembered in our hearts.",
    "Another bishop falls! Like a very civilized religious reformation with wooden participants.",
    "We lose our diagonal warrior! Their faith was strong, their strategy insufficient.",
    "Enemy claims our religious brother! Their ecclesiastical excellence has been permanently concluded.",
    "Our bishop is captured! Three points of loss, immeasurable familial chess-related grief."
  ],

  lostRook: [
    "My uncle rook falls! Our mighty fortress crumbles - five points of architectural agony!",
    "We lose a castle tower! Their straight-line strength could not save them from enemy cunning.",
    "Enemy captures our fortress! Five points of pain - like losing a very valuable, mobile building.",
    "A tower uncle is lost! Their rectangular righteousness has been unrighteously defeated.",
    "Our rook falls! Like losing family property, but more strategic and immediate.",
    "Enemy claims our castle! Their perpendicular power could not prevent their own capture.",
    "We sacrifice our fortress! Sometimes the strongest walls must fall for strategic victory.",
    "Our mighty tower is taken! Five points of structural and emotional damage sustained.",
    "A faithful rook falls! Their service was linear, their loyalty unquestionable.",
    "Enemy captures our stronghold! Alas, their defensive dreams are dashed upon offensive reality.",
    "Our uncle castle is lost! Their geometric greatness will be remembered in straight lines.",
    "Another rook falls! Like losing a cornerstone of our chess-based architectural empire.",
    "We lose our linear warrior! Their perpendicular principles could not save them from diagonal doom.",
    "Enemy claims our mighty tower! Their fortress-like qualities were impressive but insufficient.",
    "Our rook is captured! Five points of loss, immeasurable uncle-related chess grief."
  ],

  lostQueen: [
    "My beloved queen falls! Nine points of pure royal agony - the crown jewel is lost!",
    "We lose her majesty! Our multi-directional dreams are dashed upon the rocks of enemy strategy!",
    "Enemy captures our queen! Nine points of pain - like losing the heart of our chess empire!",
    "The royal piece is taken! Our eight-directional authority has been authoritatively ended!",
    "Our queen falls! Like losing one's crown, but more immediately tactical and wooden.",
    "Enemy claims our majesty! Their strategic versatility could not save them from superior cunning!",
    "We sacrifice our queen! Sometimes even royalty must fall for the greater good!",
    "Our crown jewel is lost! Nine points of sorrow - the board feels emptier already!",
    "The queen is captured! Like a royal tragedy, but with proper chess rules and less actual drama!",
    "Enemy takes our beloved! Nine points of loss, immeasurable royal chess-related heartbreak!"
  ],

  castlingKingside: [
    "Kingside castling executed! A royal dance of defensive positioning - quite elegant, really.",
    "I castle to safety! Like a very organized royal relocation with excellent timing.",
    "Kingside sanctuary achieved! The king and rook perform their ancient dance of mutual protection.",
    "Royal castling completed! Two pieces, one move - efficiency worthy of true nobility.",
    "I seek kingside shelter! Rather like moving to the countryside, but more strategic.",
    "Castling kingside accomplished! A classic maneuver, like a well-rehearsed royal waltz.",
    "The king retreats to safety! Not cowardice - strategic repositioning with style.",
    "Kingside castling performed! Ancient chess wisdom in wooden action - quite satisfying.",
    "I castle right! Like a royal emergency evacuation, but more dignified and rule-based.",
    "Royal relocation executed! The king and rook cooperate in perfect wooden harmony.",
    "Kingside sanctuary secured! Two moves for the price of one - royal efficiency at its finest.",
    "Castling completed successfully! Like a chess ballet, but with more defensive positioning.",
    "I seek protective castling! Sometimes even kings need a change of scenery and protection.",
    "Kingside dance performed! The rook and king waltz into better strategic positions.",
    "Royal castling achieved! Ancient wisdom meets modern wooden piece implementation - delightful!"
  ],

  castlingQueenside: [
    "Queenside castling executed! A longer journey, but often worth the extra squares traveled.",
    "I castle queenside! Like taking the scenic route to safety, but more strategically sound.",
    "Queenside sanctuary achieved! The long castle - for kings who prefer spacious relocation.",
    "Royal queenside positioning! Two pieces, one elegant move across multiple squares.",
    "I seek queenside shelter! Rather like moving to a larger estate with better defensive options.",
    "Castling queenside accomplished! The extended version of royal relocation - quite comprehensive.",
    "The king travels queenside! Not fleeing - strategically repositioning with appropriate ceremony.",
    "Queenside castling performed! Like a royal road trip, but shorter and more chess-related.",
    "I castle left! The longer path often leads to more interesting strategic destinations.",
    "Royal queenside relocation! The rook and king perform their extended protective dance.",
    "Queenside sanctuary secured! More squares traveled, more options gained - excellent value.",
    "Long castling completed! Like a royal procession, but more efficient and wooden.",
    "I seek queenside protection! Sometimes the longer journey provides the better destination.",
    "Queenside dance performed! The extended waltz of king and rook across multiple squares.",
    "Royal long castling achieved! Ancient wisdom meets expanded wooden piece cooperation - magnificent!"
  ],

  givingCheck: [
    "Check! Your majesty finds themselves in rather urgent need of movement!",
    "Check delivered! Their king faces immediate tactical pressure - how exciting!",
    "Royal check achieved! The enemy monarch must dance to our strategic tune!",
    "Check to the enemy king! Their royal options become suddenly quite limited!",
    "Delivering check! Like knocking on their castle door, but more strategically pressing.",
    "Check announced! Their king must respond immediately - no time for royal procrastination!",
    "Royal pressure applied! Check - their majesty's situation becomes immediately urgent!",
    "Check to their monarchy! Enemy king feels the heat of our tactical focus!",
    "Giving check! Their royal serenity is disturbed by our strategic excellence!",
    "Check delivered with pleasure! Enemy king must move or block - no royal choice in the matter!",
    "Royal check executed! Their king faces the music of our tactical symphony!",
    "Check to enemy royalty! Like a wake-up call, but more chess-related and immediate!",
    "Delivering royal pressure! Check - their king's comfort zone shrinks dramatically!",
    "Check announced proudly! Enemy monarchy faces the consequences of inferior positioning!",
    "Royal check achieved! Their king must dance, and we choose the music!",
    "Check to their majesty! Like pointing out a problem, but more tactically urgent!",
    "Giving check with style! Enemy king discovers the disadvantages of poor positioning!",
    "Royal check delivered! Their monarch must respond - royal protocol demands immediate action!",
    "Check executed perfectly! Enemy king faces the reality of our strategic superiority!",
    "Delivering check triumphantly! Their royal peace is disturbed by our wooden excellence!"
  ],

  inCheck: [
    "I am in check! Rather inconvenient - immediate royal attention required!",
    "Check against the crown! My options become suddenly quite limited - how exciting!",
    "Royal check received! Like an urgent telegram, but more wooden and immediate!",
    "I face enemy check! The situation demands swift royal decision-making!",
    "Check to my majesty! Rather like being cornered, but with proper chess protocol!",
    "Royal pressure applied! I must move, block, or... well, actually those are the options!",
    "Check against the monarchy! My royal serenity is disturbed - most inconvenient timing!",
    "I am checked! Like having one's attention forcibly focused on immediate problems!",
    "Enemy check received! The crown feels the weight of tactical pressure - quite heavy!",
    "Royal check situation! My comfortable position becomes suddenly less comfortable!",
    "Check to the king! My royal freedom of movement becomes democratically limited!",
    "I face immediate pressure! Check - the enemy demands royal response!",
    "Royal check announced! Like being served legal papers, but more chess-related!",
    "Check against my crown! The situation requires immediate royal strategic attention!",
    "I am in check! Rather like having one's afternoon tea interrupted by urgent business!",
    "Enemy check delivered! My royal options shrink to the mathematically essential!",
    "Royal pressure situation! Check - I must respond with appropriate kingliness!",
    "Check to my majesty! The crown weighs heavily when escape routes are limited!",
    "I face tactical check! Like being asked a difficult question with only specific answers!",
    "Royal check received! My sovereign comfort is disturbed by enemy wooden excellence!"
  ],

  winning: [
    "Victory appears within our grasp! Like reaching for the last biscuit and finding no competition.",
    "The tide turns in our favor! Rather like having the wind at one's back, but more chess-related.",
    "We advance toward triumph! Each move brings us closer to glorious wooden victory!",
    "Success beckons sweetly! Like a well-orchestrated symphony reaching its crescendo of chess excellence.",
    "Our position strengthens! The enemy's hopes diminish like morning mist before our strategic sun.",
    "Victory's sweet song grows louder! We conduct this chess orchestra toward inevitable triumph!",
    "The battle swings our way! Like a pendulum of fate, but more predictable and wooden.",
    "We march toward conquest! Each captured piece brings us closer to the throne of victory!",
    "Our superiority manifests! The board itself seems to favor our cause - how convenient!",
    "Triumph approaches steadily! Like a very determined tortoise with excellent chess training.",
    "The scales tip toward us! Justice and superior strategy walk hand in wooden hand!",
    "We dominate the battlefield! Like chess generals with particularly good tactical vision.",
    "Victory's crown awaits! Our wooden excellence shall be rewarded with appropriate satisfaction!",
    "The enemy weakens visibly! Their hopes fade like candlelight before our strategic hurricane!",
    "We approach the summit! Victory mountain has surprisingly chess-shaped footholds for climbing.",
    "Our triumph builds momentum! Like a snowball of success, but more geometric and immediate.",
    "The path to victory clears! Enemy resistance crumbles before our wooden determination!",
    "We seize strategic control! The board bends to our superior chess-related willpower!",
    "Victory's sweet perfume grows stronger! Success smells remarkably like... well, wooden pieces actually.",
    "Our conquest proceeds apace! Like a very organized invasion with proper documentation and rules."
  ],

  losing: [
    "The tide turns against us! Rather like swimming upstream, but with more tactical pressure.",
    "Our position weakens! Like a castle built on sand, but made of wood and following chess rules.",
    "Victory slips from our grasp! Like trying to hold water, but more immediately frustrating.",
    "The enemy gains advantage! Their success tastes bitter in our royal mouth... if we had one.",
    "We face mounting pressure! Like being squeezed in a vice, but more chess-related and polite.",
    "Our hopes diminish! Rather like watching the last train leave the station, but wooden.",
    "The scales tip away! Justice seems to have forgotten our address and strategic superiority.",
    "We fight against the current! Like salmon swimming upstream, but with less water.",
    "Enemy forces gain momentum! Their success builds like... well, like successful chess moves.",
    "Our dominance fades! Like summer giving way to autumn, but more immediate and tactical.",
    "The battle turns unfavorable! Rather like having the wind change direction at an inconvenient moment.",
    "We face strategic adversity! Like climbing uphill in a snowstorm, but with chess pieces.",
    "Victory becomes elusive! Our wooden dreams slip away like... slippery wooden things.",
    "The enemy ascends! Their triumph approaches while ours retreats to safer strategic distances.",
    "Our position crumbles! Like a sandcastle at high tide, but more organized and rule-based.",
    "Defeat looms closer! Rather like storm clouds gathering, but more chess-related.",
    "We struggle against fate! Though fate seems remarkably good at chess, unfortunately.",
    "Enemy superiority manifests! Their wooden excellence exceeds our own - most inconvenient!",
    "Our conquest stalls! Like a car running out of petrol, but with more tactical implications.",
    "The path darkens! Victory's light fades behind enemy strategic excellence - quite dramatic!"
  ],

  tidesTurning: [
    "The battle shifts dramatically! Like a seesaw of destiny with wooden participants!",
    "Fortunes reverse spectacularly! Rather like a plot twist in a chess-themed novel!",
    "The tide changes course! Our strategic ship finds new currents of possibility!",
    "Momentum shifts suddenly! Like a pendulum reversing direction with tactical precision!",
    "The tables turn magnificently! Victory and defeat dance their eternal chess waltz!",
    "Fortune's wheel spins anew! Our luck changes like weather, but more immediately relevant!",
    "The battle takes new direction! Like a river changing course, but with more strategy!",
    "Destiny shifts its favor! The chess gods smile upon... well, someone different now!",
    "The winds change suddenly! Our strategic sails must adjust to new tactical breezes!",
    "Circumstances transform dramatically! Like a caterpillar becoming a butterfly, but faster!",
    "The game's character evolves! What was lost may yet be found, what found may be lost!",
    "Strategic fortunes fluctuate! Like the stock market, but with more wooden pieces involved!",
    "The contest takes new shape! Victory's definition becomes suddenly more... flexible!",
    "Momentum swings wildly! Like a playground equipment, but with higher stakes and strategy!",
    "The narrative changes course! Our chess story finds new chapters and plot developments!"
  ],

  brilliantMove: [
    "Magnificent! A move worthy of the chess gods themselves!",
    "Brilliant strategy executed! Like poetry in wooden motion - absolutely sublime!",
    "Genius displayed! That move deserves a place in the chess hall of fame!",
    "Spectacular brilliance! I tip my royal crown to such tactical excellence!",
    "Masterstroke achieved! Like Michelangelo with a chessboard instead of marble!",
    "Pure chess artistry! That move belongs in a museum of strategic magnificence!",
    "Brilliant beyond measure! The chess angels sing hymns of that tactical beauty!",
    "Genius manifested! Like Einstein discovering relativity, but more immediately useful!",
    "Sublime strategy! That move brings tears of joy to my royal wooden eyes!",
    "Masterful execution! Like watching a master chef create the perfect soufflé of chess!",
    "Breathtaking brilliance! That tactical gem sparkles like a diamond on the board!",
    "Pure strategic gold! That move should be framed and hung in chess galleries!",
    "Transcendent excellence! Like hearing heavenly music played on wooden instruments!",
    "Divine inspiration! The chess muses surely guided that magnificent maneuver!",
    "Legendary move executed! Future generations will study that tactical masterpiece!"
  ],

  blunder: [
    "Oh dear! That move was rather... suboptimal. Everyone makes mistakes!",
    "Tactical oversight! Like stepping on a rake, but more chess-related and embarrassing!",
    "A strategic stumble! Even the best of us occasionally trip over our own pieces!",
    "Minor miscalculation! Like adding two plus two and getting... something other than four!",
    "Oopsie! That move was like trying to thread a needle while wearing boxing gloves!",
    "Tactical hiccup! Rather like sneezing during a important royal speech - unfortunate timing!",
    "Strategic slip! Like banana peel humor, but with chess pieces and immediate consequences!",
    "Chess happens! Even grandmasters occasionally move pieces to... interesting places!",
    "Learning opportunity! That move will be remembered for its... educational value!",
    "Tactical adventure! Sometimes the scenic route leads to unexpected destinations!",
    "Creative interpretation! That move certainly showed... unique strategic vision!",
    "Bold experiment! Not all innovations succeed, but points for originality!",
    "Character-building move! Adversity makes us stronger, or at least more experienced!",
    "Surprise strategy! Even we're surprised by that particular tactical choice!",
    "Memorable moment! That move will certainly be... well, remembered, anyway!"
  ],

  aboutToWin: [
    "Victory approaches like dawn! The enemy's defeat is inevitable as sunrise!",
    "Checkmate looms! Like storm clouds gathering, but more pleasant for us!",
    "The end draws near! Our wooden triumph shall echo through chess eternity!",
    "Victory's crown awaits! Just a few more moves to glorious conquest!",
    "The final act begins! Our chess opera approaches its triumphant crescendo!",
    "Conquest imminent! Like a ripe fruit ready to fall into our royal hands!",
    "The enemy's doom approaches! Their wooden fate is sealed with strategic wax!",
    "Checkmate preparation! We sharpen our tactical swords for the final blow!",
    "Victory's sweet song grows deafening! Success practically falls into our wooden lap!",
    "The endgame favors us! Like having loaded dice, but legal and strategic!",
    "Triumph inevitable! Their defeat approaches like a very determined and punctual train!",
    "The final curtain rises! Our victory performance reaches its climactic scene!",
    "Conquest within reach! Like grabbing the brass ring, but more chess-related!",
    "Checkmate preparation complete! The enemy's strategic goose is thoroughly cooked!",
    "Victory's finish line appears! Our wooden marathon nears its triumphant conclusion!"
  ],

  aboutToLose: [
    "Defeat approaches like a storm! Though storms sometimes pass without damage... hopefully!",
    "The enemy closes in! Rather like being surrounded, but with more tactical implications!",
    "Our doom draws near! Like watching a slow-motion chess catastrophe unfold!",
    "Checkmate threatens! The enemy's victory looms like a very tactical cloud!",
    "The end approaches swiftly! Our wooden fate seems... rather predetermined actually!",
    "Conquest evades us! Victory slips away like soap in a royal bathtub!",
    "The enemy's triumph builds! Like watching them build a victory sandwich while we provide ingredients!",
    "Defeat becomes probable! Rather like mathematical certainty, but more emotionally invested!",
    "Our resistance weakens! Like a castle under siege, but more wooden and immediate!",
    "The tide turns against us! Enemy victory approaches like... well, like inevitable defeat!",
    "Checkmate preparation visible! The enemy sharpens their tactical guillotine for our wooden neck!",
    "Strategic doom imminent! Like watching a chess avalanche heading straight for our position!",
    "The final act begins! Our tragedy reaches its... well, tragic conclusion!",
    "Defeat's crown awaits! Rather like being fitted for a very uncomfortable wooden hat!",
    "The enemy's endgame succeeds! Their victory approaches like a very efficient and ruthless machine!"
  ],

  checkmate: [
    "Checkmate achieved! Victory tastes as sweet as royal honey on wooden toast!",
    "The game concludes triumphantly! Our wooden excellence has been thoroughly vindicated!",
    "Checkmate delivered! Like signing a treaty of surrender, but more satisfying for us!",
    "Victory is ours! The enemy's king falls to our superior strategic methodology!",
    "Conquest complete! Our chess empire expands by exactly one game - excellent progress!",
    "Checkmate executed perfectly! Like a well-choreographed dance, but with more winning!",
    "The enemy falls! Their wooden dreams are dashed upon our tactical rocks!",
    "Victory achieved magnificently! Our triumph echoes through the halls of chess history!",
    "Checkmate! The sweet sound of wooden success fills the air around the board!",
    "Game, set, and match! Though this is chess, so it's really just... checkmate!"
  ],

  stalemate: [
    "Stalemate achieved! Rather like a very polite form of mutual strategic exhaustion!",
    "The game ends in draw! Neither army claims victory - how diplomatically wooden!",
    "Stalemate declared! Like shaking hands after a good fight, but more chess-related!",
    "Draw by stalemate! Rather like a tie in a race where nobody quite crosses the finish line!",
    "The contest concludes evenly! Honor to both sides for their wooden determination!",
    "Stalemate situation! Like reaching a fork in the road and finding both paths blocked!",
    "Draw achieved! Rather like a handshake between equals, but more strategic!",
    "The game reaches peaceful conclusion! No victor, but honor for all wooden participants!",
    "Stalemate! Like a chess détente - nobody wins, nobody loses, everyone respects rules!",
    "Draw by stalemate! Rather like a very organized form of mutual chess exhaustion!"
  ],

  draw: [
    "Draw declared! Rather like a handshake between honorable wooden combatants!",
    "The game ends evenly! Like a perfectly balanced scale with chess pieces instead of weights!",
    "Peaceful conclusion achieved! Honor to both armies for their strategic dedication!",
    "Draw by agreement! Rather like diplomatic negotiations, but more chess-related!",
    "The contest concludes in balance! Neither side claims supremacy - very sportsmanlike!",
    "Equal result achieved! Like sharing a pie evenly, but with more tactical implications!",
    "Draw situation! Rather like a very civilized form of competitive cooperation!",
    "The game reaches balanced end! Victory shared equally among wooden participants!",
    "Diplomatic draw! Like a peace treaty, but with better documentation and fewer lawyers!",
    "Equal honors distributed! Rather like everyone getting participation trophies, but earned!"
  ],

  enPassant: [
    "En passant executed! Ancient pawn law invoked with tactical precision!",
    "Special pawn capture! Like using a secret rule that everyone knows but rarely employs!",
    "En passant achieved! French tactical excellence meets English wooden implementation!",
    "Pawn law invoked! Rather like citing obscure legal precedent, but more immediately useful!",
    "Special capture executed! En passant - the ninja move of pawn warfare!",
    "Ancient rule applied! Like dusting off old chess legislation for modern tactical use!",
    "En passant successful! French strategy meets wooden execution - très magnifique!",
    "Special pawn tactics! Like a magic trick, but with proper rules and documentation!",
    "En passant capture! Ancient wisdom meets modern wooden piece implementation!",
    "Pawn law enforcement! Rather like traffic rules, but more strategic and French-influenced!"
  ],

  promotion: [
    "Pawn promotion achieved! From humble peasant to noble royalty - the American dream!",
    "Transformation complete! Our little pawn becomes a queen - rather inspiring really!",
    "Promotion successful! Like a fairy tale, but with proper chess rules and less magic!",
    "Pawn elevation! From foot soldier to royalty - the ultimate career advancement!",
    "Metamorphosis achieved! Our humble piece becomes magnificent - pure chess poetry!",
    "Royal promotion! Rather like knighting someone, but with more immediate tactical benefits!",
    "Pawn transformation! From caterpillar to butterfly, but wooden and more strategically useful!",
    "Promotion complete! Our peasant achieves royalty - social mobility at its finest!",
    "Noble elevation! Like Cinderella, but with chess pieces and better documentation!",
    "Pawn coronation! From humble origins to royal status - the chess dream realized!"
  ],

  sacrifice: [
    "Noble sacrifice made! Sometimes the greatest gifts require the highest prices!",
    "Tactical sacrifice executed! Like offering oneself for the greater good, but more strategic!",
    "Heroic sacrifice! Our piece falls so others may live and capture enemy forces!",
    "Strategic offering made! Rather like throwing oneself on a grenade, but more chess-related!",
    "Noble sacrifice completed! The ultimate tactical generosity - giving one's position for victory!",
    "Heroic tactical gift! Our piece sacrifices itself on the altar of strategic necessity!",
    "Sacrifice for the cause! Rather like martyrdom, but with better mathematical justification!",
    "Strategic sacrifice executed! Sometimes the greatest victories require the highest costs!",
    "Noble offering made! Our piece gives its wooden life for the greater chess good!",
    "Tactical martyrdom! Rather like heroic literature, but with more immediate practical benefits!",
    "Heroic sacrifice achieved! Like throwing oneself into battle, but more calculated and wooden!",
    "Strategic gift delivered! Our piece's sacrifice paves the road to wooden victory!",
    "Noble tactical offering! Sometimes the greatest strategies require the greatest sacrifices!",
    "Heroic piece sacrifice! Like epic poetry, but more mathematically sound and immediate!",
    "Strategic martyrdom complete! Our fallen piece's legacy lives on in tactical victory!"
  ],

  fork: [
    "Fork executed! Like holding two conversations simultaneously, but more tactically devastating!",
    "Double attack achieved! Rather like killing two birds with one very strategic stone!",
    "Fork tactics successful! One move, two threats - efficiency worthy of royal approval!",
    "Double threat delivered! Like juggling, but with more immediate strategic consequences!",
    "Fork attack completed! Rather like a chess two-for-one special with tactical excellence!",
    "Dual pressure applied! Like squeezing two lemons with one hand, but more strategic!",
    "Fork maneuver executed! Two problems for the enemy, one solution for us - mathematics!",
    "Double tactical strike! Rather like lightning hitting twice, but more predictable!",
    "Fork achieved magnificently! Like a chess wishbone, but with more immediate benefits!",
    "Dual attack successful! Two targets, one move - strategic efficiency at its wooden finest!"
  ],

  pin: [
    "Pin executed perfectly! Enemy piece frozen like a deer in very tactical headlights!",
    "Pinning attack achieved! Rather like holding someone's coat while they try to leave!",
    "Pin tactics successful! Their piece becomes strategically paralyzed - quite satisfying!",
    "Immobilization complete! Like casting a spell, but with proper chess rules and documentation!",
    "Pin maneuver executed! Enemy piece stuck like... well, like a pinned chess piece!",
    "Tactical paralysis achieved! Rather like strategic acupuncture with wooden needles!",
    "Pin attack successful! Their piece frozen in tactical amber for our advantage!",
    "Strategic immobilization! Like putting someone in checkmate timeout, but more immediate!",
    "Pin executed with precision! Enemy piece becomes a very expensive wooden decoration!",
    "Tactical freezing completed! Rather like winter arriving early for that particular piece!"
  ]
};

export function getWhiteKingDialogue(category) {
  if (!whiteKingDialogues[category]) return null;
  const phrases = whiteKingDialogues[category];
  return phrases[Math.floor(Math.random() * phrases.length)];
}